export type Lang = "en" | "vi";

export const translations = {
  en: {
    appTitle: "AI Video Factory",
    appSubtitle: "AI Story & Video",
    creditBalance: "Credits",
    costEstimate: "Cost",
    projects: "Projects",
    newProject: "New Project",
    vietnamLanguage: "VI",
    englishLanguage: "EN",
    Generation_Mode: "Generation Mode",
    Labs_Flow_Mode: "Flow Veo 3",
    Gemini_Chat_Mode: "Gemini Room",
    Gemini_Pro: "Gemini 3.1 Pro",
    Gemini_Flash: "Gemini 3.5 Flash",
    Gemini_Flash_Lite: "Gemini 3.1 Flash-Lite",
    Generate_Type: "Generate Type",
    Drawing_Model: "Model",
    createNew: "Create",
    noProjects: "Empty list",
    projectName: "Name",
    projectDesc: "Description",
    cancel: "Cancel",
    confirm: "Recreate",
    confirmRecreateTitle: "Recreate All Images",
    confirmRecreateMessage: "All scenes already have images. Do you want to recreate all of them?",
    create: "Create",
    saving: "Saving...",
    save: "Save",
    delete: "Delete",
    confirmDelete: "Confirm deletion?",
    editProject: "Edit",
    credits: "Credits",
    stepShortLabels: ["Script", "Storyboard", "Covers", "SEO", "Export", "Generate Image/Video", "CapCut Editor"],
    stepTooltips: [
      "Input ideas and generate script",
      "Segment scenes, direct visual style, generate prompts, and synthesize scene-by-scene voices",
      "Produce cover assets and click-bait thumbnail instructions",
      "Increase search discoverability and estimate CTR performance",
      "Export CapCut templates, Premiere XML, or render preview WebM/MP4",
      "Independent batch image and video generator with Labs Flow & Gemini Chat",
      "Advanced automation, Image-to-Audio matching, dynamic panning effects, and AI Sound Effects for CapCut draft projects",
    ],
    stepInput: "1. Script",
    stepVoice: "2. Storyboard",
    stepStoryboard: "2. Storyboard",
    stepAssets: "3. Covers",
    stepSEO: "4. SEO",
    stepExport: "5. Export",
    sourceType: "Source Type",
    originalScript: "Original Script",
    originalScriptDesc: "Paste script to rewrite.",
    storyIdea: "Story Idea",
    storyIdeaDesc: "Enter a brief concept.",
    inputPlaceholder: "Enter text...",
    videoGenre: "Genre",
    outputLang: "Language",
    targetDuration: "Duration",
    rewriteLevel: "Rewrite Level",
    similarityReduction: "Uniqueness",
    creativityLevel: "Creativity",
    factCheck: "Fact Check",
    factCheckDesc: "Verify facts and names.",
    targetAudience: "Audience",
    writingStyle: "Writing Style",
    generatePipeline: "Generate",
    hookConfigTitle: "Hook Settings",
    hookType: "Hook Type",
    hookDuration: "Duration (s)",
    hookCount: "Count",
    hookPositions: "Strategy",
    hookPosStart: "Start Only",
    hookPosMid: "Start & Mid",
    hookPosAll: "Start, Mid & End",
    generateHooks: "Generate Hooks",
    selectingHookDesc: "Select most engaging option.",
    regenerate: "Regenerate",
    useSelectedHook: "Apply",
    enhancedScript: "Enhanced Script",
    factCheckResult: "Logs",
    chaptersList: "Chapters",
    editScriptDesc: "Refine lines as needed.",
    generateStoryboard: "Build Storyboard",
    storyboardDirector: "Storyboard",
    storyboardSubtitle: "Click cards to edit.",
    sceneId: "Scene",
    playPreview: "Simulate",
    sceneEditor: "Edit Scene",
    sceneText: "Text",
    sceneSubtitle: "Subtitles",
    imagePrompt: "Image Prompt",
    cameraMotion: "Motion",
    fx: "Effects",
    transition: "Transition",
    generateImage: "Render Scene",
    renderingImage: "Rendering visual...",
    renderSuccess: "Success!",
    renderFailed: "Render failed.",
    assetMgr: "Thumbnail Generator",
    uploadMapping: "Manual Mapping",
    uploadSceneAssets: "Upload Scene Asset",
    mixedMode: "Asset Priority",
    thumbnailHeader: "Thumbnail Ideas",
    bulkRenderThumbnails: "Bulk Render Mockups",
    bulkRenderThumbnails_loading: "Rendering all thumbnails...",
    generateThumbnail: "Analyze Thumbnail",
    withText: "With Text",
    withoutText: "No Text",
    textText: "Slogan",
    layoutSuggestion: "Composition",
    typography: "Font Tip",
    colors: "Palette",
    focus: "Focal Point",
    voiceConfig: "Voice Sync",
    provider: "Voice Engine",
    gender: "Gender",
    age: "Age",
    emotion: "Emotion",
    speechRate: "Speed",
    generateAudio: "Synthesize Audio",
    synthesizing: "Synthesizing voice...",
    listenTest: "Listen",
    uploadedAudio: "Upload Audio",
    seoOptimizer: "SEO Boost",
    seoDescription: "Select AI descriptive metadata with computed engagement probability.",
    searchability: "Search Demand",
    ctrProb: "Expected CTR",
    compRatio: "Competition",
    hashtags: "Hashtags",
    tags: "Keywords",
    exportCenter: "Export Suite",
    renderTitle: "Render Simulation",
    renderingWebM: "Export Video",
    exportCapcut: "Export CapCut Project",
    exportPremiere: "Adobe Premiere XML",
    exportDavinci: "DaVinci Resolve XML",
    downloadZip: "Download ZIP Project",
    cloudSync: "Sync Online Storage",
    shareSocial: "Publish Social Channels",
    localRenderMode: "Use Local GPU",
    flowInput: "Input",
    flowHook: "Hook",
    flowRewrite: "Script",
    flowStoryboard: "Storyboard",
    flowVisual: "Visuals",
    flowVoice: "Voiceover",
    flowSEO: "SEO",
    flowExport: "Export",
    viewPipelineMap: "View Pipeline",
    Please_enter_script_conte: "Please enter script content or narrative concept.",
    MULTI_STEP_SYSTEM_FLOW_Dr: "[MULTI-STEP SYSTEM FLOW] Drafting script...",
    Generation_completed_The_: "Generation completed! The script is ready.",
    Loaded_current_scenes_sto: "Loaded current scenes storyboard!",
    Missing_detailed_script_f: "Missing detailed script for storyboarding.",
    MULTI_STEP_SYSTEM_FLOW_Fo: "[MULTI-STEP SYSTEM FLOW] Formulating storyboard...",
    Storyboard_coordinates_fo: "Storyboard coordinates formulated successfully!",
    Scene_visual_prompt_copie: "Scene visual prompt copied to clipboard successfully!",
    Hook_content_copied_to_cl: "Hook content copied to clipboard successfully!",
    No_scenes_available_to_co: "No scenes available to copy prompts!",
    Pure_optimized_scene_prom: "Pure optimized scene prompts list copied to clipboard!",
    MULTI_STEP_SYSTEM_FLOW_Ex: "[MULTI-STEP SYSTEM FLOW] Extracting visual style...",
    Style_extracted_successfu: "Style extracted successfully!",
    No_scenes_to_apply_style: "No scenes to apply style!",
    No_style_extracted_yet: "No style extracted yet!",
    Applying_style_to_scenes: "Applying style to scenes...",
    Successfully_applied_styl: "Successfully applied style to scenes!",
    Applied_style_fallback_mo: "Applied style (fallback mode)!",
    No_matching_image_files_f: "No matching image files found to align with scenes!",
    Rewriting_thumbnail_promp: "Rewriting thumbnail prompts to match new style...",
    Thumbnail_style_extracted: "Thumbnail style extracted successfully!",
    No_thumbnails_to_apply_style: "No cover pages to apply style.",
    Deleted_scene_image_succe: "Deleted scene image successfully!",
    No_storyboard_scenes_foun: "No storyboard scenes found to generate images!",
    Detailed_image_prompt_gen: "Detailed image prompt generated successfully!",
    Scene_mod_saved_successfu: "Scene mod saved successfully.",
    Loaded_current_Thumbnail_: "Loaded current Thumbnail drafts!",
    Missing_detailed_script_f_1: "Missing detailed script for thumbnails.",
    MULTI_STEP_SYSTEM_FLOW_De: "[MULTI-STEP SYSTEM FLOW] Designing thumbnails...",
    High_engagement_Thumbnail: "High engagement Thumbnail drafts drawn!",
    Mockup_thumbnail_painted_: "Mockup thumbnail painted successfully!",
    Generating_and_preparing_: "Generating and preparing download...",
    You_must_generate_the_sto: "You must generate the storyboard before downloading (the system uses sequential generation).",
    Voiceover_downloaded_succ: "Voiceover downloaded successfully!",
    MULTI_STEP_SYSTEM_FLOW_Ge: "[MULTI-STEP SYSTEM FLOW] Generating voiceover...",
    You_must_generate_the_sto_2: "You must generate the storyboard before synthesizing the scene-by-scene voiceover!",
    No_scenes_to_generate_voi: "No scenes to generate voiceovers for!",
    Script_is_empty: "Script is empty!",
    MULTI_STEP_SYSTEM_FLOW_Ge_3: "[MULTI-STEP SYSTEM FLOW] Generating voiceover for the entire story...",
    charScriptEmpty: "Script is empty, please generate storyboard script first.",
    charAnalyzing: "Analyzing main character of the script...",
    charAnalyzeSuccess: "Successfully analyzed main character!",
    charAnalyzeFailed: "Failed to analyze character.",
    charExtracting: "Extracting character design reference from images...",
    charExtractSuccess: "Successfully extracted character reference!",
    charExtractFailed: "Failed to extract character reference.",
    charNoScenes: "No scenes to apply character design.",
    charNoPrompt: "No character prompt extracted yet.",
    charApplying: "Rewriting visual prompts incorporating character details...",
    charApplySuccess: "Successfully applied character reference to all scenes!",
    charApplyFallback: "Applied character reference (fallback mode)!",
    charApplyFailed: "Failed to apply character reference.",
    charConsistencyTitle: "Character Consistency",
    charDetected: "Detected Main Character:",
    charNotAnalyzed: "Main character not analyzed from script yet.",
    charAnalyzeBtn: "Analyze Character",
    charUploadTitle: "Upload Character Images",
    charUploadDrop: "Drag & drop reference images here",
    charPromptTitle: "Character Details",
    charCopied: "Character prompt copied to clipboard!",
    charDescCopied: "Character description copied to clipboard!",
    charExtractingBtn: "Extracting...",
    charExtractBtn: "Extract Reference",
    charApplyingBtn: "Applying...",
    charApplyBtn: "Apply",
    charNoImages: "No character images uploaded.",
    charDetectedCount: "Detected {count} main characters:",
    charReAnalyze: "Re-analyze",
    charApplyAll: "Apply All",
    Apply_Character_Thumbnails: "Apply",
    charCopyDesc: "Copy character description",
    charUploadFor: "Upload {name}",
    charNoImagesFor: "No images uploaded for {name}",
    deleteAllImagesBtn: "Delete All Images",
    deleteAllImagesConfirm: "Are you sure you want to delete all generated and uploaded images for all scenes? This action cannot be undone.",
    deleteAllImagesSuccess: "Successfully deleted all scene images!",
    favVoicesTitle: "Favorite Voices",
    favVoicesEmpty: "No favorite voices saved yet.",
    addFavVoiceBtn: "Add Voice",
    voiceNamePlaceholder: "Voice Name",
    voiceIdPlaceholder: "Voice ID (Voice URI)",
    channelNamePlaceholder: "Channel/Provider Name",
    applyFavVoice: "Apply",
    deleteFavVoice: "Delete",
    saveCurrentVoice: "Save Current",
    voiceNameRequired: "Please enter a voice name",
    voiceIdRequired: "Please enter a Voice ID",
    saveVoiceSuccess: "Voice saved to favorites!",
    applyVoiceSuccess: "Voice actor applied!",
    voiceNameCopied: "Voice name copied to clipboard!",
    voiceIdCopied: "Voice ID copied to clipboard!",
    updateVoiceSuccess: "Voice updated successfully!",
    favStylesTitle: "Styles",
    favStylesEmpty: "No saved styles yet.",
    addFavStyleBtn: "Add",
    styleNamePlaceholder: "Name",
    stylePromptPlaceholder: "Prompt",
    saveCurrentStyle: "Save Style",
    styleNameRequired: "Please enter a style name",
    stylePromptRequired: "Please enter a style prompt",
    saveStyleSuccess: "Style saved!",
    applyStyleSuccess: "Style applied!",
    styleNameCopied: "Style name copied!",
    stylePromptCopied: "Style prompt copied!",
    updateStyleSuccess: "Style updated!",
    copiedScript: "Voiceover script copied!",
    copiedSubtitle: "Subtitle line copied!",
    copiedPrompt: "AI image prompt copied!",
    Synthesized_full_story_vo: "Synthesized full story voiceover successfully!",
    Loaded_current_SEO_draft: "Loaded current SEO draft!",
    Missing_detailed_script_f_4: "Missing detailed script for SEO optimization.",
    MULTI_STEP_SYSTEM_FLOW_An: "[MULTI-STEP SYSTEM FLOW] Analyzing SEO...",
    SEO_metrics_formulated_su: "SEO metrics formulated successfully!",
    Preparing_rendering: "Preparing rendering...",
    Cinematic_simulated_video: "Cinematic simulated video downloaded successfully!",
    Failed_to_compile_video_C: "Failed to compile video. Check audio context permissions.",
    No_subtitles_or_descripti: "No subtitles or description written yet",
    Packaging_project: "Packaging project...",
    Rendering_video: "Rendering video...",
    Syncing_scene_voices: "Syncing scene voices...",
    Package_ZIP_created_succe: "🎉 Package ZIP created successfully! Fully matches CapCut PC Desktop active draft format specifications.",
    Error_generating_template: "❌ Error generating template bundle ZIP. Please check and retry.",
    Back_to_projects: "Back to projects",
    Projects: "Projects",
    Pro: "Pro",
    Step_Flow_L_key: "Step Flow (L key)",
    Settings_R_key: "Settings (R key)",
    System_Logs: "System Logs",
    No_logs_available: "No logs available.",
    FLOW_WORKSPACE: "FLOW WORKSPACE",
    NODES: "NODES",
    NODE: "NODE_",
    FPS_24_COMPLIANT: "FPS-24 | COMPLIANT",
    Select_your_story_materia: "Select your story materials, format target lengths and tweak Gemini coefficients.",
    N_i_dung_c_t_truy_n: "Nội dung cốt truyện",
    Nh_p_n_i_dung_k_ch_b_n_nh: "Nhập nội dung, kịch bản nháp hoặc ý tưởng sơ bộ...",
    C_u_h_nh_K_ch_b_n: "Cấu hình Kịch bản",
    Th_lo_i_video: "Thể loại video",
    Ng_n_ng_u_ra: "Ngôn ngữ đầu ra",
    Ti_ng_Vi_t: "🇻🇳 Tiếng Việt",
    Ti_ng_Anh: "🇺🇸 Tiếng Anh",
    C_u_h_nh_S_l_ng_t_Th_i_l_: "Cấu hình Số lượng từ & Thời lượng",
    AI_s_bu_c_ph_i_m_r_ng_n_i: "AI sẽ buộc phải mở rộng nội dung để kịch bản bám sát\n                        đúng chỉ tiêu từ này.",
    Kh_n_gi_m_c_ti_u: "Khán giả mục tiêu",
    Phong_c_ch_h_nh_v_n: "Phong cách hành văn",
    C_ng_Vi_t_l_i: "Cường độ Viết lại",
    Gi_m_tr_ng_l_p: "Giảm trùng lặp",
    s_ng_t_o: "Độ sáng tạo",
    X_c_th_c_th_ng_tin_Fact_c: "Xác thực thông tin (Fact check)",
    T_ng_ph_n_t_ch_v_x_c_minh: "Tự động phân tích và xác minh độ chuẩn xác của các\n                          thông tin.",
    Ph_n_t_ch_t_ng_v_bi_n_so_: "Phân tích ý tưởng và biên soạn kịch bản chi tiết tự động",
    ang_t_o: "Đang tạo...",
    Generate_Script: "Generate Script",
    ang_so_n_k_ch_b_n: "Đang soạn kịch bản...",
    M_h_nh_AI_ang_ki_n_t_o_k_: "Mô hình AI đang kiến tạo kịch bản thuyết minh đầy\n                              đủ chi tiết bằng luồng thuật toán đa bước.",
    FULL_VERBOSE_SCRIPT: "FULL VERBOSE SCRIPT",
    Copied_script: "Copied script!",
    Copy: "Copy",
    Words: "Words",
    Chars: "Chars",
    Est_Time: "Est. Time",
    min: "min",
    Fact_Check_Insight: "Fact Check Insight",
    Analyzing_historical_data: "Analyzing historical data...",
    Chapters_Script_Outline: "Chapters Script Outline",
    Chapter: "Chapter",
    Continue: "Continue",
    Scene_Voiceovers: "Scene Voiceovers",
    Design_sequential_visual_: "Design sequential visual slides and generate professional voiceovers for each individual scene.",
    Automatically_split_story: "Automatically split story scenes",
    Processing: "Processing...",
    Generate_Storyboard: "Generate Storyboard",
    Settings: "Settings",
    Fullscreen: "Fullscreen",
    fullscreenError: "Error attempting to enable fullscreen: {error}",
    txt_1_Voice_Actor: "1. Voice Actor",
    Select_voice: "Select voice...",
    Test_voice: "Test voice",
    Generate_all_scene_voiceo: "Generate all scene voiceovers",
    Loading: "Loading...",
    Generate_Voice: "Generate Voice",
    txt_2_Split_Density: "2. Split Density",
    Word_aligned_Maximizes_im: "Word-aligned - Maximizes image correlation",
    By_word: "⏱️ By word",
    Fast_paced_vibrant_short_: "Fast-paced, vibrant short clauses",
    Short_sentence: "⚡ Short sentence",
    Default_balanced_standard: "Default, balanced standard full sentence",
    Long_sentence: "⚖️ Long sentence",
    Mixed_sentences_desc: "A smart blend of short, punchy sentences and detailed standard sentences",
    Mixed_sentences: "🎭 Mixed Short & Long Sentences",
    Logical_paragraph_aligned: "Logical paragraph-aligned narration flow",
    Paragraph_density: "📖 Paragraph density",
    Master_Narration_Voiceove: "Master Narration Voiceover",
    LIVE_AUDIO_READY: "LIVE AUDIO READY",
    Audio_rendering_preview: "Audio rendering preview",
    Live_playing: "Live playing",
    Deck_ready: "Deck ready",
    Synthesizing_voice: "Synthesizing voice...",
    Building_audio_waves_and_: "Building audio waves and aligning timeline subtitle markings.",
    No_voiceover_synthesized_: "No voiceover synthesized yet",
    AI_Speech_Channel: "AI Speech Channel",
    Female_Speaker: "Female Speaker",
    Male_Speaker: "Male Speaker",
    Standard_Speaker: "Standard Speaker",
    txt_16_bit_WAV: "16-bit WAV",
    txt_44_1kHz_Mono: "44.1kHz • Mono",
    Click_to_toggle_speech_ra: "Click to toggle speech rate",
    x: "x",
    Download_voiceover_file: "Download voiceover file",
    DL_VOICE: "DL VOICE",
    Console_Synchronization_l: "Console - Synchronization ledger",
    Copied_alignments_ledger: "Copied alignments ledger!",
    SYSTEM: "[SYSTEM]",
    Launching_Real_time_Align: "Launching Real-time Alignment Engine...",
    PROCESS_Generating_audio_: "[PROCESS] Generating audio wave...",
    Console_is_waiting_for_ti: "Console is waiting for timing logs...",
    Storyboard_splitting_path: "Storyboard splitting path",
    Select_Storyboard_Split_M: "Select Storyboard Split Mode",
    Switching_to_Audio_Voice_: "Switching to Audio Voice split mode",
    Audio_voice_mode: "Audio voice mode",
    Recommended: "Recommended",
    Align_scenes_timings_dyna: "Align scenes timings dynamically triggered by the voiceover audio source.",
    Switching_to_full_text_sc: "Switching to full text script mode",
    Script_mode: "Script mode",
    Utilize_raw_screenplay_sc: "Utilize raw screenplay script lines to sync scenes cuts prompts.",
    AI_Speech: "AI Speech",
    External_Audio: "External Audio",
    Female_speaker_AI: "Female speaker AI",
    Male_speaker_AI: "Male speaker AI",
    Standard_voice: "Standard voice",
    Smart_aligned_timeline_vo: "Smart aligned timeline voiceover",
    Reset: "Reset",
    AI_Voice: "AI Voice",
    Simulated_Voice: "Simulated Voice",
    Synthesized_audio_demo: "Synthesized audio demo",
    Exit_synth: "Exit synth",
    AI_voiceover_not_compiled: "AI voiceover not compiled",
    Compile_AI_speech_at_step: "Compile AI speech at step 1 or trigger simulated TTS voice below.",
    Sample_Speech: "Sample Speech",
    Activated_simulated_speec: "Activated simulated speech fallback!",
    Simulated_Voice_5: "Simulated Voice",
    Linked_external_narration: "Linked external narration",
    Replace: "Replace",
    Remove: "Remove",
    Drop_audio_file_now: "Drop audio file now...",
    Drag_audio_or_Click_to_up: "Drag audio or Click to upload",
    Supported_up_to_50MB_wav_: "Supported up to 50MB wav, mp3 formats",
    Paste_verbose_storyboard_: "Paste verbose storyboard scenes script here...",
    Tip_Pasting_full_narratio: "Tip: Pasting full narration content results in highly aligned image cues.",
    Modify_visual_configurati: "Modify visual configurations",
    Veo_3_Creative_Studio_Dec: "Veo 3 Creative Studio Deck",
    Collapse: "Collapse",
    Expand: "Expand",
    Active_Drawing_Engine: "Active Drawing Engine:",
    IMAGE_REFERENCE_NODE: "IMAGE REFERENCE NODE",
    Upload_style_images: "Upload style images",
    System_extracts_Style_Art: 'System extracts "Style/Art Medium"',
    Style: "Style:",
    Copied_style: "Copied style!",
    Copy_style: "Copy style",
    Extracting: "Extracting...",
    Extract_Style: "Extract Style",
    Applying: "Applying...",
    Apply_Style: "Apply Style",
    No_reference_images_uploa: "No reference images uploaded yet.",
    Bulk_visuals_sync_suite: "Bulk visuals sync suite",
    Export_all_scene_prompts_: "Export all scene prompts instantly and sync finished external images back in one batch.",
    Step_1_Bulk_copy_raw_prom: "Step 1: Bulk copy raw prompts",
    Copy_all_chronological_sc: "Copy all chronological scene prompts instantly with no decorators to generate outside.",
    Copied_successfully: "Copied successfully!",
    Copy_All: "Copy All",
    Step_2_Batch_upload_scene: "Step 2: Batch upload scene images",
    Drag_drop_all_generated_i: "Drag & drop all generated images or click to select them from local directories.",
    How_auto_alignment_works: "📌 How auto-alignment works:",
    H_th_ng_s_ng_b_theo_t_n_f: "Hệ thống sẽ đồng bộ theo tên file dạng:",
    txt_1_jpg: "1.jpg",
    txt_2_jpg: "2.jpg",
    ho_c_ch_a_ch_s_t_ng_ng_v_: ", hoặc chứa chữ số tương ứng với Phân cảnh. Nếu tên\n                          không khớp số, hệ thống tự động gắn tệp theo thứ tự\n                          chữ cái",
    A_Z: "A-Z",
    ph_n_ph_i_u_t_u_n_cu_i: "phân phối đều từ đầu đến cuối.",
    Aligns_based_on_number_in: "Aligns based on number indicators within file name:\n                          e.g.",
    or: "or",
    scene_2_jpg: "scene_2.jpg",
    Otherwise_distributes_sor: ".\n                          Otherwise distributes sorted filenames alphabetically\n                          (A-Z) sequentially.",
    Auto_Render_All_Scene_Art: "Auto Render All Scene Artwork",
    Process_all_storyboard_de: "Process all storyboard descriptions sequentially. Runs up to 10 scene images per request block to comply with API security standards.",
    Trigger_batch_AI_renderin: "Trigger batch AI rendering for all scene visualizations",
    BATCH_RENDER: "BATCH RENDER",
    OPTIMIZE_PROMPTS: "Optimize AI",
    optimizingPrompts: "Optimizing...",
    optimizePromptsSuccess: "Successfully improved image descriptions!",
    No_Storyboard_Scenes: "No Storyboard Scenes",
    Click_button_below_to_sub: "Click button below to subdivide script into scenes with precise visual guidelines.",
    Generating_all_voices: "Generating all voices...",
    MULTI_STEP_SYSTEM_FLOW_Di: "[MULTI-STEP SYSTEM FLOW] Dividing scenes...",
    System_is_synthesizing_te: "System is synthesizing text-to-speech for all scenes.",
    Mapping_detailed_timeline: "Mapping detailed timelines to separate storyboard scenes.",
    Drawing: "Drawing...",
    s: "s",
    No_AI_image: "No AI image",
    No_description: "No description",
    Go_to_previous_page: "Go to previous page",
    Previous: "Previous",
    Go_to_next_page: "Go to next page",
    Next: "Next",
    Scene_Inspector: "Scene Inspector",
    s_6: "s)",
    Scene_Artwork: "Scene Artwork",
    No_AI_Artwork_Rendered: "No AI Artwork Rendered",
    Render_AI_image_matching_: "Render AI image matching the scene narration strictly",
    Regen_AI: "Regen AI",
    Render_AI: "Render AI",
    Upload_file: "Upload file",
    Delete_Image: "Delete Image",
    Duration: "Duration",
    Camera_motion: "Camera motion",
    FX: "FX",
    Narration_text: "Narration text",
    Subtitle: "Subtitle",
    Designer: "Designer",
    Hide: "Hide",
    Show: "Show",
    txt_1_Environment_Setting: "1. Environment / Setting:",
    misty_pine_forest_vintage: "misty pine forest, vintage library...",
    txt_2_Time_of_Day_Lighting: "2. Time of Day & Lighting:",
    warm_golden_sunset_low_ke: "warm golden sunset, low key light...",
    txt_3_Character_details: "3. Character details:",
    old_wise_magician: "old wise magician...",
    txt_4_Costume_Attire: "4. Costume & Attire:",
    rough_leather_boots: "rough leather boots...",
    txt_5_Camera_Angle: "5. Camera Angle:",
    cinematic_close_up_portra: "cinematic close up portrait...",
    Writing: "Writing...",
    Optimize_Prompt: "Optimize Prompt",
    E_g_Blur: "E.g. Blur",
    E_g_Fade: "E.g. Fade",
    Cancel: "Cancel",
    Save_Changes: "Save Changes",
    Back: "Back",
    Select_visual_styles_defi: "Select visual styles, define mapping properties of assets or design high CTR YouTube icons.",
    Create_prompt_guides_and_: "Create prompt guides and phantoms of high CTR mockups",
    Generating: "Generating...",
    Generate_Thumbnails: "Generate Thumbnails",
    Thumbnail_Prompts_Input: "Thumbnail Prompts Input",
    INPUT_STATE: "INPUT STATE",
    Empty_script_Paste_here: "Empty script. Paste here.",
    Batch_Count: "Batch Count:",
    idea: "idea",
    ideas: "ideas",
    Reference_Image_Optional: "Reference Image (Optional)",
    Style_copied: "Style copied",
    No_Thumbnail_Prompts: "No Thumbnail Prompts",
    bulkRenderThumbnailsSuccess: "Bulk thumbnail rendering completed successfully!",
    Draft_eye_catching_visual: "Draft eye-catching visual arrangements and high-contrast styling settings.",
    Draft_visual_arrangements: "Draft visual arrangements for your YouTube mockup icons",
    Generate_Thumbnail: "Generate Thumbnail",
    Drafting_CTR_thumbnail: "Drafting CTR thumbnail...",
    Drafting_eye_catching_vis: "Drafting eye-catching visual arrangements and color grading palettes.",
    thumbnail: "thumbnail",
    No_Render_Done: "No Render Done",
    Look: "Look",
    Copied_thumbnail_prompt: "Copied thumbnail prompt!",
    Copy_Prompt: "Copy Prompt",
    Layout: "Layout",
    Font: "Font",
    Color: "Color",
    Render_YouTube_mockup_thu: "Render YouTube mockup thumbnail using AI",
    Render_Mockup: "Render Mockup",
    Recreate_Mockup: "Recreate",
    Form_tts_voices_with_dive: "Form tts voices with diverse emotions then lock alignments directly with speech subtitles.",
    Run_speech_audio_synthesi: "Run speech audio synthesizer for narration script",
    Synthesizing: "Synthesizing...",
    Synthesize_Voice: "Synthesize Voice",
    Full_verbose_script: "Full verbose script",
    txt_1_Vocal_timbre_expression: "1. Vocal timbre & expression characteristics",
    Choose_narrator_voices_em: "Choose narrator voices, emotional empathy profiles and synthetic vocal presets.",
    System_Cloud_Speaker: "System & Cloud Speaker",
    Requires_Vietnamese_voice: "Requires Vietnamese voice",
    NARRATOR: "NARRATOR",
    CLOUD_AI: "CLOUD AI",
    NATIVE_TTS: "NATIVE TTS",
    Male: "Male",
    Female: "Female",
    Neutral: "Neutral",
    Custom_custom_defined_syn: "Custom custom-defined synthesizer",
    Northern_female: "Northern female",
    Northern_male: "Northern male",
    Central_female: "Central female",
    Central_male: "Central male",
    Southern_female: "Southern female",
    Southern_male: "Southern male",
    Playful_kids_voiceover: "Playful kids voiceover",
    Google_free_female: "Google free female",
    Google_free_male: "Google free male",
    Google_free_English_femal: "Google free English female",
    FPT_female_monthly: "FPT female monthly",
    FPT_male_monthly: "FPT male monthly",
    Zalo_female_daily: "Zalo female daily",
    Viettel_male_yearly: "Viettel male yearly",
    Hifidelity_native_female_: "Hifidelity native female cloud AI",
    Deep_speaker_native_male_: "Deep speaker native male cloud AI",
    Muff_free_high_quality_cl: "Muff-free high quality cloud TTS",
    Local_offline_system_voic: "Local offline system voice",
    Cloud_online_voice: "Cloud online voice",
    Speed: "Speed:",
    Pitch: "Pitch:",
    Stop_preview: "Stop preview",
    Preview_current_voice: "Preview current voice",
    Change_voice: "Change voice",
    Male_Voice: "Male Voice",
    Female_Voice: "Female Voice",
    Neutral_Accent: "Neutral Accent",
    txt_2_Acoustic_master_control: "2. Acoustic master controllers",
    Refine_playback_rates_emo: "Refine playback rates, emotional voice pitch and scale volume metrics.",
    Speed_7: "Speed",
    txt_0_5x: "0.5x",
    txt_2_0x: "2.0x",
    Pitch_8: "Pitch",
    Volume: "Volume",
    Mute: "Mute",
    Synchronicity_Journal: "Synchronicity Journal",
    Aligned: "Aligned",
    Click_the_button_below_to: "Click the button below to synthesize automatically or upload your own audio voice track.",
    Synthesize_AI_Voice: "Synthesize AI Voice",
    Alignment_Console_Ready: "Alignment Console Ready",
    Once_voiceover_is_synthes: "Once voiceover is synthesized, detailed records of forced alignment matching, scene splits, and accuracy will be listed visually.",
    syncing: "(syncing...)",
    CONFIG: "[CONFIG]",
    Mapping_timelines_to_scen: "Mapping timelines to scenes...",
    STATUS: "[STATUS]",
    Aligning_subtitles: "Aligning subtitles...",
    Synchronizing: "Synchronizing...",
    Forced_alignment_matches_: "Forced alignment matches words in audio",
    Optimize_metadata_and_tri: "Optimize metadata and trigger smart tag recommendations",
    Optimizing: "Optimizing...",
    Optimize_SEO: "Optimize SEO",
    SEO_Optimization_Input: "SEO Optimization Input",
    Number_of_Title_Variants_: "Number of Title Variants to Generate",
    variants: "variants",
    Titles_Options_Group: "Titles Options Group",
    No_SEO_Data: "No SEO Data",
    Click_Optimize_Boost_at_t: 'Click"Optimize / Boost"at the top to draft metadata.',
    Copied_title_to_clipboard: "Copied title to clipboard!",
    Copy_title: "Copy title",
    Search: "Search:",
    CTR: "CTR:",
    Compet: "Compet:",
    SEO_Score: "SEO Score:",
    Description_Options: "Description Options",
    Descriptions_are_empty: "Descriptions are empty.",
    Copied_description_to_cli: "Copied description to clipboard!",
    Copied_Hashtags_to_clipbo: "Copied Hashtags to clipboard!",
    Copy_Hashtags: "Copy Hashtags",
    No_hashtags: "No hashtags",
    Copied_Tags_to_clipboard: "Copied Tags to clipboard!",
    Copy_Tags: "Copy Tags",
    No_keywords: "No keywords",
    rendering_visual: "rendering visual",
    Default_Timeline_Image: "Default Timeline Image",
    Scene: "Scene",
    Camera_VFX: "Camera VFX",
    Nothing_to_simulate: "Nothing to simulate.",
    SIMULATOR_STATUS: "SIMULATOR STATUS:",
    ACTIVE_RUNNING: "ACTIVE RUNNING",
    PAUSED: "PAUSED",
    Stop_Simulation: "Stop Simulation",
    Play_Simulation: "Play Simulation",
    Professional_Project_Pack: "Professional Project Packaging",
    Exports_timeline_JSON_fil: "Exports timeline JSON file compatible with CapCut Desktop.",
    Construct_XML_track_metad: "Construct XML track metadata for Adobe workflows.",
    Download_FCPXML_timing_fi: "Download FCPXML timing file matching DaVinci formats.",
    Render_and_compile_full_p: "Render and compile full panoramic cinematic video session with camera motions and subtitles.",
    Download_complete_CapCut_: "Download complete CapCut PC active draft folder bundle including full subdirectories and timeline templates.",
    Download_SRT: "Download SRT",
    Extract_synced_subtitle_t: "Extract synced subtitle timestamps file.",
    Cloud_Exporter_Sync_Setup: "Cloud Exporter Sync Setup",
    https_s3_amazonaws_com_yo: "https://s3.amazonaws.com/your-bucket",
    Configured_bucket_coordin: "Configured bucket coordinates successfully!",
    Save: "Save",
    Image_Lightbox_Preview: "Image Lightbox Preview",
    Generation_Prompt: "Generation Prompt",
    Download_Original: "Download Original",
    Close_window: "Close window",
    Voice_Registry: "Voice Registry",
    Voices: "Voices",
    Search_voices_registry_by: "Search voices registry by moniker, language code, locale...",
    Cloud_AI_Premium: "Cloud AI (Premium)",
    Offline_Local_TTS: "Offline Local TTS",
    LOCALE: "LOCALE:",
    All: "All",
    Vietnamese: "Vietnamese",
    English: "English",
    Premium_studio_quality_vo: "Premium studio-quality voices for realistic storytelling narration.",
    GENDER: "GENDER:",
    Male_9: "Male",
    Female_10: "Female",
    No_speakers_found_matchin: "No speakers found matching filters",
    Adjust_search_query_revok: "Adjust search query, revoke gender exclusions or toggle Cloud / Offline tabs.",
    FEMALE: "FEMALE",
    MALE: "MALE",
    NEUTRAL: "NEUTRAL",
    Hifidelity_female_cloud_A: "Hifidelity female cloud AI",
    Hifidelity_male_cloud_AI: "Hifidelity male cloud AI",
    Muff_free_cloud_AI_defaul: "Muff-free cloud AI defaults",
    Offline_system_synthesize: "Offline system synthesizer",
    Online_speech_voice: "Online speech voice",
    Offline_Supported: "Offline Supported",
    Online_API_Required: "Online API Required",
    Listen_sample: "Listen sample",
    ACTIVE: "ACTIVE",
    SELECT: "SELECT",
    Switching_locks_subtitles: "Switching locks subtitles.",
    APPLY: "APPLY",
    WORKSPACE: "WORKSPACE",
    PROPS: "PROPS",
    General_Metadata: "General Metadata",
    Project_Hash: "Project Hash",
    Content_Target_Lang: "Content Target Lang",
    Format_Strategy: "Format Strategy",
    Active_Profiles: "Active Profiles",
    Narrator_ID: "Narrator ID",
    Vision_Identity: "Vision Identity",
    System_Error: "System Error",
    Success: "Success",
    Failed_to_parse_cURL_comm: "✗ Failed to parse cURL command",
    v2_4_PRO: "v2.4 PRO",
    Live_Sync: "Live Sync",
    pts: "pts",
    USD: "USD",
    Sandbox: "Sandbox",
    text_slate_400_hover_text: "text-slate-400 hover:text-slate-200",
    VI: "VI",
    EN: "EN",
    Sandbox_Config: "Sandbox Config",
    Active: "Active",
    Unlimited_Proxy: "Unlimited Proxy",
    Saved: "Saved!",
    Paste_cURL_from_Chrome_F1: "Paste cURL from Chrome (F12)",
    Paste_full_cURL: "Paste full cURL...",
    Extracted_Parameters: "Extracted Parameters",
    Authorization: "Authorization",
    Project_ID: "Project ID",
    Session_ID: "Session ID",
    API_Mode: "API Mode",
    Saving: "Saving...",
    Save_Config: "Save Config",
    Synthesize_stories_design: "Synthesize stories, design visual timelines, and export.",
    en_US: "en-US",
    No_description_1: "No description...",
    Open: "Open",
    Confirm_Deletion: "Confirm Deletion",
    Are_you_sure_you_want_to_: "Are you sure you want to delete the project",
    This_action_cannot_be_und: "This action cannot be undone. All scripts and configurations will be permanently removed.",
    Edit_Project: "Edit Project",
    E_g_Legends_of_Rome: "E.g., Legends of Rome",
    Write_custom_script_idea_: "Write custom script idea metrics...",
    Niche_ideas: "Niche ideas",
    You_can_choice_History_Do: "You can choice History, Documentary or Science genre to generate accurate prompts for rendering with Imagen 4.",
    Update: "Update",
    Inputs: "Inputs",
    Hook_Engine: "Hook Engine",
    Story_Expansion: "Story Expansion",
    Storyboard: "Storyboard",
    Visuals: "Visuals",
    Audio_Sync: "Audio & Sync",
    SEO_Boost: "SEO Boost",
    Video_Editorial: "Video Editorial",
    Click_any_node_to_view_de: "Click any node to view detailed logic",
    STAGE_0: "STAGE 0",
    Navigate_to_this_stage: "Navigate to this stage",
    Jump_to_this_step: "Jump to this step",
    Close: "Close",
    Voice_Library: "Voice Library",
    Search_2: "Search",
    Name_description: "Name, description...",
    Provider: "Provider",
    Edge_Microsoft: "Edge (Microsoft)",
    ElevenLabs: "ElevenLabs",
    Minimax: "Minimax",
    Kokoro: "Kokoro",
    Clone: "Clone",
    Vbee: "Vbee",
    Language: "Language",
    English_3: "English",
    Vietnamese_4: "Vietnamese",
    French: "French",
    German: "German",
    Spanish: "Spanish",
    Japanese: "Japanese",
    Korean: "Korean",
    Chinese: "Chinese",
    Gender: "Gender",
    Male_5: "Male",
    Female_6: "Female",
    Age: "Age",
    Young: "Young",
    Middle_aged: "Middle-aged",
    Elderly: "Elderly",
    No_voices_found: "No voices found",
    Loading_7: "Loading...",
    Selected: "Selected",
    Loading_8: "Loading...",
    Image_Generation_Settings: "Image Generation Settings",
    Image: "Image",
    Video: "Video",
    Aspect_Ratio: "Aspect Ratio",
    Input_Method_Labs: "Input Method (Labs)",
    Type_Text: "Type Text",
    Quick_Paste: "Quick Paste",
    Sample_Count: "Sample Count",
    Imagen_3: "✨ Imagen 3",
    Nano_Banana_2: "🍌 Nano Banana 2",
    Labs_Sandbox: "🧪 Labs Sandbox",
    Chrome_Mode: "Chrome Mode",
    Chrome_Hidden: "Run Hidden (Headless)",
    Chrome_Visible: "Open Browser (Headful)",
    Generation_Speed: "Generation Speed (tabs)",
    GeminiSpeed_1: "1",
    GeminiSpeed_3: "3",
    GeminiSpeed_5: "5",
    GeminiSpeed_7: "7",
    GeminiSpeed_10: "10",
    Batch_Delay: "Batch Delay",
    Batch_Delay_Default: "Default (1-2s)",
    Batch_Delay_1s: "1s",
    Batch_Delay_2s: "2s",
    Batch_Delay_3s: "3s",
    Batch_Delay_Random_123: "Random 1-3s",
    cancellingBatchGen: "Cancelling batch image generation...",
    initializingBatchGen: "Initializing batch image generation...",
    batchGenCancelled: "Process cancelled. Successfully generated {completedCount} images.",
    generatingSceneBatch: "Generating scene {sceneId} ({currentIndex}/{totalToProcess})...",
    errorRenderingSceneBatch: "Error rendering scene {sceneId}: {error}",
    waitingBetweenScenes: "Waiting 3 seconds before next scene...",
    batchGenSuccess: "Successfully completed sequential generation of all {completedCount} scene images!",
    batchGenFailed: "Error during batch image generation: {error}",
    alignmentLoaded: "Subtitles sync loaded.",
    scriptPipelineError: "Script error: {error}",
    syncLedgerSuccess: "=== VOICE TIMING SYNC SUCCESS ({totalDuration}s) ===\n",
    syncLedgerItem: '👉 Scene {index} ({startTime} --> {endTime}) | {duration}s | Sub: "{script}..."\n',
    storyboardPipelineError: "Storyboard error: {error}",
    imagePipelineError: "Image generation error: {error}",
    imageUploadSuccess: "Image uploaded for Scene {sceneId}!",
    styleExtractionError: "Style extraction failed: {error}",
    applyStyleError: "Failed to apply style: {error}",
    missingImagesWarning: "⚠️ Missing images for Scenes: {ids}.",
    mismatchImagesWarning: '⚠️ Name/Scene index mismatch: file "{fileName}" -> Scene {sceneId}.',
    bulkUploadSuccess: "Successfully synced {count} images!",
    promptGenError: "Prompt generation error: {error}",
    thumbnailPipelineError: "Thumbnail generation error: {error}",
    voiceSynthError: "AI voice generation failed: {error}",
    errorGeneratingVoiceover: "Voiceover generation failed: {error}",
    seoPipelineError: "SEO optimization failed: {error}",
    renderingProgress: "Exporting video: {prog}%...",
    stopImageGen: "Stop Image Generation",
    cancelling: "Cancelling...",
    ext_success_extract: "✓ Successfully parsed:",
    ext_bearer: "Bearer, ",
    ext_recaptcha: "reCAPTCHA, ",
    ext_streamchat: "StreamChat (SSE)",
    ext_batch: "Batch",
    apiKeysConfig: "API Keys Configuration",
    configured: "Configured",
    notSet: "Not Set",
    apiKeysDesc: "These keys take precedence over options in your .env file",
    enterGeminiKey: "Enter Google Gemini API Key...",
    enterAi33Key: "Enter AI33 TTS Token...",
    favorite: "Favorite",
    copyVoiceName: "Copy voice name",
    editVoice: "Edit voice",
    deleteVoice: "Delete voice",
    copyStyleDesc: "Copy style description",
    editStyle: "Edit style",
    deleteStyle: "Delete style",
    loadedFile: "Loaded file: {name}",
    pasteSamplePrompts: "Paste sample stickman prompts",
    clearAll: "Clear all",
    charNamePlaceholder: "Character name",
    charBioPlaceholder: "Character biography...",
    noImageYet: "No image yet",
    charFeaturePlaceholder: "Character features...",
    composition169: "16:9 Composition",
    focusTitle: "Focus",
    downloadImage: "Download image",
    uploadingImage: "Uploading...",
    deleting: "Deleting...",
    copyNarration: "Copy narration",
    copySubtitle: "Copy subtitle",
    copyAiImagePrompt: "Copy AI image prompt",
    totalScenesCount: "Total Scenes: {count}",
    pageIndicator: "Page {current} of {total}",
    noPhotoRenderedYet: "No photo rendered yet for SCENE {sceneId}. Go back and render!",
    offlineRenderProgressText: "Rendering progress: {progress}%...",
    streamNotSupported: "Data stream is not supported by this browser.",
    aligningVoiceWithWhisper: "Syncing audio via Whisper AI...",
    voiceAlignSuccess: "Successfully aligned scene durations 1-1 with real voice (Whisper AI)!",
    voiceAlignNoValidResult: "No valid analysis result returned from Whisper AI.",
    voiceAlignSceneNotFound: "Synchronization data not found for scene {sceneId}.",
    voiceAlignError: "Voice synchronization via Whisper AI failed. Please check your Python/Whisper installation.",
    exportingCapcut: "Exporting CapCut...",
    exportingPremiere: "Exporting Premiere...",
    exportingDavinci: "Exporting DaVinci...",
    exportingVideo: "Rendering Video...",
    packagingZip: "Packaging ZIP...",
    exportingSRT: "Exporting SRT...",
    waitExportProcess: "Please wait a moment, this process may take some time...",
    download: "Download",
    node6_settings_title: "Independent Creator Settings",
    node6_engine: "Generation Engine",
    node6_engine_veo3: "Flow Veo 3 (Labs Flow)",
    node6_engine_gemini: "Gemini Room (Gemini Chat)",
    node6_gen_type: "Generate Type",
    node6_image: "Image",
    node6_video: "Video",
    node6_aspect_ratio: "Aspect Ratio",
    node6_prompts_list: "Prompts List",
    node6_sample_prompts: "Sample Prompts",
    node6_clear_workspace: "Clear Workspace",
    node6_placeholder: "Paste prompts here, one per line...\nExample:\n1. A stickman walking in rain...\n2. A stickman holding a sword...",
    node6_detected_prompts: "Detected: {count} prompts",
    node6_stop_gen: "STOP GENERATION",
    node6_start_gen: "START BATCH GENERATION",
    node6_zip_tooltip: "Download all ZIP",
    node6_console_title: "Generation Output Aligner",
    node6_console_waiting: "Waiting to launch alignment engine...",
    node6_library_title: "Independent Library Deck",
    node6_library_empty: "No Prompts Entered",
    node6_library_empty_desc: "Enter a list of prompt descriptions on the left to begin rendering artwork or video segments.",
    node6_prompt_label: "Prompt {id}",
    node6_badge_done: "DONE",
    node6_badge_error: "ERR",
    node6_rendering: "Rendering...",
    node6_waiting: "Waiting...",
    node6_log_sample_loaded: "Sample prompts loaded.",
    node6_log_invalid_prompts: "Please enter at least one valid prompt.",
    node6_log_start: "Starting independent generation flow...",
    node6_log_cancelled: "Generation cancelled by user.",
    node6_log_processing: "Processing prompt {index}/{total}...",
    node6_log_success: "Successfully generated prompt {index} in {duration}s.",
    node6_log_api_error: "API returned failure without specific warning",
    node6_log_error: "Error at prompt {index}: {error}",
    node6_log_completed: "All prompts process complete.",
    node6_log_cancelling: "Sending cancel signal...",
    node6_log_zip_empty: "No successful assets to pack in ZIP.",
    node6_log_zip_start: "Initializing ZIP compression...",
    node6_log_zip_success: "ZIP downloaded successfully!",
    node6_log_zip_error: "ZIP packing failed: {error}",
    node6_log_cleared: "Workspace cleared.",
    node7_title: "CapCut Editor",
    node7_desc: "Automation, Image-to-Audio syncing, Dynamic Motion, and AI Sound Effects for CapCut draft projects.",
    node7_input_file_label: "1. Target draft_content.json file",
    node7_choose_file_btn: "Browse Draft",
    node7_file_selected: "Selected: {name}",
    node7_file_empty: "No draft_content.json file chosen",
    node7_api_key_label: "2. Google Gemini API Key (Required for AI SFX)",
    node7_api_key_placeholder: "Enter Gemini API Key here...",
    node7_sfx_folder_label: "3. Sound Effects Directory (Optional)",
    node7_choose_sfx_btn: "Browse SFX",
    node7_sfx_selected: "SFX Folder: {path}",
    node7_sfx_empty: "No SFX folder selected",
    node7_status_ready: "READY TO PROCESS",
    node7_status_processing: "PROCESSING...",
    node7_status_success: "PROCESS COMPLETED!",
    node7_status_failed: "PROCESS FAILED",
    node7_status_canceled: "PROCESS CANCELED",
    node7_run_btn: "LAUNCH PROCESS",
    node7_select_all: "Select All",
    node7_deselect_all: "Deselect All",
    node7_console_title: "Ultra Process Terminal",
    node7_console_waiting: "Waiting to execute CapCut Ultra process...",
    node7_log_started: "CapCut Ultra execution sequence initiated...",
    node7_log_success: "CapCut Ultra completed successfully!",
    node7_log_error: "CapCut Ultra execution failed: {error}",
    node7_log_missing_file: "Please select a draft_content.json file first!",
    node7_log_missing_api: "Gemini API key is required when AI Sound Effect Generator is enabled!",
    node7_log_missing_sfx: "Sound Effects directory is required when AI Sound Effect Generator is enabled!",
    node7_opt_sync: "1. Sync Image/Video to Voice 1-1",
    node7_opt_music_mix: "2. Ultra Music Mix (Random Background Music)",
    node7_opt_custom_order: "3. Custom Audio Track Order",
    node7_opt_randomize: "4. Randomize Video Timeline",
    node7_opt_motion: "5. Auto Zoom & Pan / Dynamic Motion",
    node7_opt_transition: "6. Auto Transition Insert",
    node7_opt_clear_trans: "7. Clear All Existed Transitions",
    node7_opt_fill_canvas: "8. Auto Scale Fit Canvas 9:16 / 16:9",
    node7_opt_normalize: "9. Auto Normalize Audio Volume",
    node7_opt_reverse: "10. Reverse Timeline Sequence",
    node7_opt_subtitles: "11. Auto Font / Subtitle Preset Config",
    node7_opt_sfx: "12. AI Sound Effect Generator",
    node7_placeholder_file: "Absolute path to draft_content.json...",
    node7_placeholder_sfx: "Absolute path to Sound Effects folder...",
    node7_placeholder_audio_list: "e.g. intro, voice, outro",
    node7_opt_title: "Automation Options",
    node7_audio_order_label: "Custom audio tracks order list:",
    node7_log_started_dialog: "Opening file dialog...",
    node7_log_started_folder: "Opening folder dialog...",
    node7_log_selected_file: "Selected file: {path}",
    node7_log_selected_folder: "Selected folder: {path}",
    node7_log_canceled_file: "File selection canceled.",
    node7_log_canceled_folder: "Folder selection canceled.",
    node7_log_error_file: "Error selecting file: {error}",
    node7_log_error_folder: "Error selecting folder: {error}",
    node7_log_calling_backend: "Calling backend to execute Python subprocess...",
    node7_log_backup_saved: "Backup file was saved in the same directory (.backup_ultra).",
    dashboardCreatorInfo: "Creator Info",
    dashboardAICreator: "AI Creator",
    dashboardMemberPro: "Member V2.4 Pro",
    dashboardCreditsBalance: "Credits Balance",
    dashboardPoints: "pts",
    dashboardSyncedRealtime: "Synced in real-time",
    dashboardEstimatedCost: "Estimated Cost",
    dashboardAI_Metrics: "AI operations metrics",
    dashboardLatestProject: "Latest Project",
    dashboardNoDesc: "No description available.",
    dashboardOpenStudio: "Open Studio",
    dashboardWelcome: "Welcome to Vidify Studio",
    dashboardWelcomeDesc: "Create a new AI video project in Content tab to start your automated video production journey.",
    dashboardGoToContent: "Go to Content",
  },
  vi: {
    appTitle: "Dựng Phim AI",
    appSubtitle: "Biên kịch & dựng phim tự động",
    creditBalance: "Số dư",
    costEstimate: "Chi phí",
    projects: "Dự án",
    newProject: "Dự án mới",
    vietnamLanguage: "VI",
    englishLanguage: "EN",
    Generation_Mode: "Chế độ sinh",
    Labs_Flow_Mode: "Flow Veo 3",
    Gemini_Chat_Mode: "Gemini Room",
    Gemini_Pro: "Gemini 3.1 Pro",
    Gemini_Flash: "Gemini 3.5 Flash",
    Gemini_Flash_Lite: "Gemini 3.1 Flash-Lite",
    Generate_Type: "Loại tạo",
    Drawing_Model: "Mô hình vẽ",
    createNew: "Tạo mới",
    noProjects: "Danh sách trống",
    projectName: "Tên",
    projectDesc: "Mô tả",
    cancel: "Hủy",
    confirm: "Tạo lại",
    confirmRecreateTitle: "Tạo lại tất cả",
    confirmRecreateMessage: "Tất cả phân cảnh đã có ảnh. Bạn muốn tạo lại tất cả?",
    create: "Tạo",
    saving: "Đang lưu...",
    save: "Lưu",
    delete: "Xóa",
    confirmDelete: "Xác nhận xóa?",
    editProject: "Sửa",
    credits: "Tín dụng",
    stepShortLabels: ["Kịch bản", "Phân cảnh", "Ảnh bìa", "Tối ưu SEO", "Kết xuất", "Tạo ảnh/video", "Biên tập CapCut"],
    stepTooltips: ["Ý tưởng & kịch bản", "Dàn cảnh, tạo lời thoại và giọng đọc cho từng phân cảnh.", "Thiết kế ảnh bìa", "Tối ưu hóa tìm kiếm SEO", "Kết xuất thành phẩm", "Tạo ảnh/video độc lập bằng Veo 3 hoặc Gemini Room.", "Tự động khớp ảnh, chỉnh góc quay và tạo hiệu ứng âm thanh AI cho CapCut."],
    stepInput: "1. Kịch bản",
    stepVoice: "2. Phân cảnh",
    stepStoryboard: "2. Phân cảnh",
    stepAssets: "3. Ảnh bìa",
    stepSEO: "4. SEO",
    stepExport: "5. Kết xuất",
    sourceType: "Đầu vào",
    originalScript: "Kịch bản gốc",
    originalScriptDesc: "Dán kịch bản để viết lại.",
    storyIdea: "Ý tưởng",
    storyIdeaDesc: "Nhập ý tưởng ngắn.",
    inputPlaceholder: "Nhập văn bản...",
    videoGenre: "Thể loại",
    outputLang: "Ngôn ngữ",
    targetDuration: "Thời lượng",
    rewriteLevel: "Mức viết lại",
    similarityReduction: "Độ độc bản",
    creativityLevel: "Sáng tạo",
    factCheck: "Kiểm thực tế",
    factCheckDesc: "Xác minh thông tin.",
    targetAudience: "Khán giả",
    writingStyle: "Văn phong",
    generatePipeline: "Tiếp tục",
    hookConfigTitle: "Cấu hình Hook",
    hookType: "Loại Hook",
    hookDuration: "Thời lượng (s)",
    hookCount: "Tùy chọn",
    hookPositions: "Chiến thuật",
    hookPosStart: "Mở đầu",
    hookPosMid: "Đầu & Giữa",
    hookPosAll: "Toàn bộ",
    generateHooks: "Tạo Hook",
    selectingHookDesc: "Chọn câu thu hút nhất.",
    regenerate: "Tạo lại",
    useSelectedHook: "Áp dụng",
    enhancedScript: "Kịch bản",
    factCheckResult: "Xác thực",
    chaptersList: "Chương",
    editScriptDesc: "Chỉnh sửa nếu cần.",
    generateStoryboard: "Tạo cảnh",
    storyboardDirector: "Phân cảnh",
    storyboardSubtitle: "Nhấn vào thẻ để sửa.",
    sceneId: "Cảnh",
    playPreview: "Chạy thử",
    sceneEditor: "Sửa cảnh",
    sceneText: "Thuyết minh",
    sceneSubtitle: "Phụ đề",
    imagePrompt: "Prompt vẽ",
    cameraMotion: "Góc quay",
    fx: "Kỹ xảo",
    transition: "Chuyển cảnh",
    generateImage: "Vẽ ảnh",
    renderingImage: "Đang vẽ hình...",
    renderSuccess: "Đã vẽ xong!",
    renderFailed: "Tự động khôi phục.",
    assetMgr: "Tạo bìa",
    uploadMapping: "Đồng bộ",
    uploadSceneAssets: "Tải ảnh",
    mixedMode: "Ưu tiên",
    thumbnailHeader: "Ý tưởng bìa",
    bulkRenderThumbnails: "Tạo hàng loạt",
    bulkRenderThumbnails_loading: "Đang tạo...",
    generateThumbnail: "Phân tích bìa",
    withText: "Kèm tiêu đề",
    withoutText: "Không chữ",
    textText: "Slogan bìa",
    layoutSuggestion: "Bố cục",
    typography: "Font chữ",
    colors: "Màu sắc",
    focus: "Tiêu điểm",
    voiceConfig: "Giọng đọc",
    provider: "Giọng đọc",
    gender: "Giới tính",
    age: "Độ tuổi",
    emotion: "Biểu cảm",
    speechRate: "Tốc độ",
    generateAudio: "Tạo voice",
    synthesizing: "Đang tạo giọng...",
    listenTest: "Nghe thử",
    uploadedAudio: "Tải âm thanh",
    seoOptimizer: "Tối ưu SEO",
    seoDescription: "Tiêu đề, mô tả và từ khóa tối ưu.",
    searchability: "Tìm kiếm",
    ctrProb: "Tỷ lệ CTR",
    compRatio: "Cạnh tranh",
    hashtags: "Từ khóa",
    tags: "Hashtags",
    exportCenter: "Xuất bản",
    renderTitle: "Xem thử",
    renderingWebM: "Tải Video (.mp4)",
    exportCapcut: "Xuất CapCut",
    exportPremiere: "Xuất Premiere",
    exportDavinci: "Xuất DaVinci",
    downloadZip: "Tải ZIP",
    cloudSync: "Lưu Cloud",
    shareSocial: "Chia sẻ",
    localRenderMode: "Dựng cục bộ",
    flowInput: "Ý tưởng",
    flowHook: "Dẫn dắt",
    flowRewrite: "Kịch bản",
    flowStoryboard: "Phân cảnh",
    flowVisual: "Hình ảnh",
    flowVoice: "Lồng tiếng",
    flowSEO: "SEO",
    flowExport: "Xuất bản",
    viewPipelineMap: "Bộ điều phối",
    Please_enter_script_conte: "Vui lòng nhập kịch kịch bản hoặc ý tưởng trước.",
    MULTI_STEP_SYSTEM_FLOW_Dr: "[MULTI-STEP SYSTEM FLOW] Đang sáng tác kịch bản...",
    Generation_completed_The_: "Sáng tác thành công! Kịch bản đã sẵn sàng.",
    Loaded_current_scenes_sto: "Đã tải danh sách phân cảnh hiện tại!",
    Missing_detailed_script_f: "Chưa có kịch bản chi tiết để dàn dựng.",
    MULTI_STEP_SYSTEM_FLOW_Fo: "[MULTI-STEP SYSTEM FLOW] Đang dàn dựng phân cảnh...",
    Storyboard_coordinates_fo: "Đã xây dựng bản phân cảnh chi tiết!",
    Scene_visual_prompt_copie: "Đã sao chép nội dung mô tả hình ảnh phân cảnh thành công!",
    Hook_content_copied_to_cl: "Đã sao chép nội dung hook thành công!",
    No_scenes_available_to_co: "Không có phân cảnh nào để sao chép!",
    Pure_optimized_scene_prom: "Đã sao chép toàn bộ danh sách miêu tả âm thầm vào bộ nhớ tạm!",
    MULTI_STEP_SYSTEM_FLOW_Ex: "[MULTI-STEP SYSTEM FLOW] Đang phân tích phong cách hình ảnh...",
    Style_extracted_successfu: "Đã trích xuất phong cách thành công!",
    No_scenes_to_apply_style: "Chưa có phân cảnh nào để áp dụng!",
    No_style_extracted_yet: "Chưa có phong cách nào được trích xuất!",
    Applying_style_to_scenes: "Đang áp dụng phong cách cho các phân cảnh...",
    Successfully_applied_styl: "Áp dụng phong cách vào phân cảnh thành công!",
    Applied_style_fallback_mo: "Đã áp dụng phong cách (chế độ dự phòng)!",
    No_matching_image_files_f: "Không tìm thấy tệp ảnh phù hợp để sắp xếp vào các phân cảnh!",
    Rewriting_thumbnail_promp: "Đang viết lại các ảnh bìa theo phong cách mới...",
    Thumbnail_style_extracted: "Trích xuất phong cách ảnh bìa thành công!",
    No_thumbnails_to_apply_style: "Chưa có ảnh bìa để áp dụng phong cách.",
    Deleted_scene_image_succe: "Đã xóa ảnh phân cảnh thành công!",
    No_storyboard_scenes_foun: "Không có phân cảnh nào để tạo ảnh!",
    Detailed_image_prompt_gen: "Đã tạo Câu Lệnh tạo ảnh chi tiết thành công!",
    Scene_mod_saved_successfu: "Đã lưu chỉnh sửa phân cảnh thành công",
    Loaded_current_Thumbnail_: "Đã tải danh sách hình thu nhỏ hiện tại!",
    Missing_detailed_script_f_1: "Chưa có kịch bản chi tiết để tạo hình thu nhỏ.",
    MULTI_STEP_SYSTEM_FLOW_De: "[MULTI-STEP SYSTEM FLOW] Đang thiết kế hình thu nhỏ...",
    High_engagement_Thumbnail: "Đã thiết kế kế hoạch hình thu nhỏ tỷ lệ nhấp kích hoạt cao!",
    Mockup_thumbnail_painted_: "Ảnh bìa mẫu thử đã được phác họa hoàn thành!",
    Generating_and_preparing_: "Đang chuẩn bị tạo và tải file...",
    You_must_generate_the_sto: "Bạn cần Dàn dựng phân cảnh (Bước 3) trước khi hệ thống có thể tải về (vì cần xử lý tuần tự từng cảnh).",
    Voiceover_downloaded_succ: "Tải giọng đọc thuyết minh thành công!",
    MULTI_STEP_SYSTEM_FLOW_Ge: "[MULTI-STEP SYSTEM FLOW] Đang khởi tạo bộ thuyết minh...",
    charScriptEmpty: "Hãy tạo kịch bản trước.",
    charAnalyzing: "Đang phân tích nhân vật...",
    charAnalyzeSuccess: "Phân tích nhân vật thành công!",
    charAnalyzeFailed: "Phân tích thất bại.",
    charExtracting: "Đang trích xuất nhân vật...",
    charExtractSuccess: "Trích xuất thành công!",
    charExtractFailed: "Trích xuất thất bại.",
    charNoScenes: "Không có phân cảnh.",
    charNoPrompt: "Chưa có đặc tả nhân vật.",
    charApplying: "Đang áp dụng nhân vật...",
    charApplySuccess: "Đã áp dụng nhân vật.",
    charApplyFallback: "Đã áp dụng đặc tả nhân vật chính (Chế độ dự phòng).",
    charApplyFailed: "Lỗi khi áp dụng đặc tả nhân vật.",
    charConsistencyTitle: "Nhân vật chính",
    charDetected: "Nhân vật chính phát hiện:",
    charNotAnalyzed: "Chưa phân tích nhân vật.",
    charAnalyzeBtn: "Phân tích",
    charUploadTitle: "Tải ảnh nhân vật",
    charUploadDrop: "Kéo thả ảnh tại đây",
    charPromptTitle: "Đặc tả nhân vật",
    charCopied: "Đã copy prompt nhân vật!",
    charDescCopied: "Đã copy mô tả!",
    charExtractingBtn: "Đang trích xuất...",
    charExtractBtn: "Trích xuất",
    charApplyingBtn: "Đang áp dụng...",
    charApplyBtn: "Áp dụng",
    charNoImages: "Chưa có ảnh nhân vật.",
    charDetectedCount: "Tìm thấy {count} nhân vật:",
    charReAnalyze: "Phân tích lại",
    charApplyAll: "Áp dụng hết",
    Apply_Character_Thumbnails: "Áp dụng",
    charCopyDesc: "Copy mô tả",
    charUploadFor: "Tải ảnh {name}",
    charNoImagesFor: "Thiếu ảnh {name}",
    deleteAllImagesBtn: "Xóa tất cả",
    deleteAllImagesConfirm: "Bạn có chắc chắn muốn xóa tất cả hình ảnh đã tạo và tải lên của toàn bộ các phân cảnh không? Hành động này không thể hoàn tác.",
    deleteAllImagesSuccess: "Đã xóa tất cả ảnh!",
    favVoicesTitle: "Giọng đọc yêu thích",
    favVoicesEmpty: "Chưa lưu giọng đọc nào.",
    addFavVoiceBtn: "Thêm giọng",
    voiceNamePlaceholder: "Tên giọng đọc",
    voiceIdPlaceholder: "Voice ID (Voice URI)",
    channelNamePlaceholder: "Tên kênh / Provider",
    applyFavVoice: "Áp dụng",
    deleteFavVoice: "Xóa",
    saveCurrentVoice: "Lưu giọng",
    voiceNameRequired: "Vui lòng nhập tên giọng đọc",
    voiceIdRequired: "Vui lòng nhập Voice ID",
    saveVoiceSuccess: "Đã lưu giọng đọc!",
    applyVoiceSuccess: "Đã áp dụng giọng!",
    voiceNameCopied: "Đã sao chép tên!",
    voiceIdCopied: "Đã sao chép mã giọng!",
    updateVoiceSuccess: "Đã cập nhật giọng!",
    favStylesTitle: "Phong cách",
    favStylesEmpty: "Chưa lưu phong cách nào.",
    addFavStyleBtn: "Thêm",
    styleNamePlaceholder: "Tên",
    stylePromptPlaceholder: "Mô tả",
    saveCurrentStyle: "Lưu phong cách",
    styleNameRequired: "Vui lòng nhập tên phong cách",
    stylePromptRequired: "Vui lòng nhập mô tả phong cách",
    saveStyleSuccess: "Đã lưu!",
    applyStyleSuccess: "Đã áp dụng!",
    styleNameCopied: "Đã sao chép tên!",
    stylePromptCopied: "Đã sao chép mô tả!",
    updateStyleSuccess: "Đã cập nhật!",
    copiedScript: "Đã sao chép thuyết minh!",
    copiedSubtitle: "Đã sao chép phụ đề!",
    copiedPrompt: "Đã sao chép prompt vẽ!",
    You_must_generate_the_sto_2: "Vui lòng dàn dựng cảnh trước.",
    No_scenes_to_generate_voi: "Không có cảnh để tạo voice.",
    Script_is_empty: "Kịch bản trống!",
    MULTI_STEP_SYSTEM_FLOW_Ge_3: "Đang tạo giọng đọc toàn bộ...",
    Synthesized_full_story_vo: "Đã tạo voice toàn bộ!",
    Loaded_current_SEO_draft: "Đã tải đề xuất SEO.",
    Missing_detailed_script_f_4: "Thiếu kịch bản để tối ưu SEO.",
    MULTI_STEP_SYSTEM_FLOW_An: "Đang phân tích SEO...",
    SEO_metrics_formulated_su: "Tối ưu SEO thành công!",
    Preparing_rendering: "Đang chuẩn bị kết xuất...",
    Cinematic_simulated_video: "Đã tải video xuống.",
    Failed_to_compile_video_C: "Lỗi kết xuất video.",
    No_subtitles_or_descripti: "Thiếu phụ đề hoặc mô tả.",
    Packaging_project: "Đang đóng gói...",
    Rendering_video: "Đang xuất video...",
    Syncing_scene_voices: "Đang đồng bộ voice...",
    Package_ZIP_created_succe: "🎉 Đã đóng gói dự án CapCut (.ZIP) thành công!",
    Error_generating_template: "❌ Lỗi đóng gói. Hãy thử lại.",
    Back_to_projects: "Quay lại dự án",
    Projects: "Dự án",
    Pro: "Pro",
    Step_Flow_L_key: "Sơ đồ Bước (Phím L)",
    Settings_R_key: "Cài đặt (R)",
    System_Logs: "Nhật ký",
    No_logs_available: "Chưa có log nào.",
    FLOW_WORKSPACE: "KHÔNG GIAN LÀM VIỆC",
    NODES: "CÁC BƯỚC",
    NODE: "NODE_",
    FPS_24_COMPLIANT: "FPS-24 | CHUẨN",
    Select_your_story_materia: "Nhập cốt truyện, thời lượng và chọn mô hình AI.",
    N_i_dung_c_t_truy_n: "Cốt truyện",
    Nh_p_n_i_dung_k_ch_b_n_nh: "Nhập cốt truyện hoặc ý tưởng...",
    C_u_h_nh_K_ch_b_n: "Cài đặt kịch bản",
    Th_lo_i_video: "Thể loại video",
    Ng_n_ng_u_ra: "Ngôn ngữ đầu ra",
    Ti_ng_Vi_t: "🇻🇳 Tiếng Việt",
    Ti_ng_Anh: "🇺🇸 Tiếng Anh",
    C_u_h_nh_S_l_ng_t_Th_i_l_: "Số từ & Thời lượng",
    AI_s_bu_c_ph_i_m_r_ng_n_i: "AI sẽ buộc phải mở rộng nội dung để kịch bản bám sát\n                        đúng chỉ tiêu từ này.",
    Kh_n_gi_m_c_ti_u: "Khán giả",
    Phong_c_ch_h_nh_v_n: "Văn phong",
    C_ng_Vi_t_l_i: "Viết lại",
    Gi_m_tr_ng_l_p: "Giảm trùng",
    s_ng_t_o: "Sáng tạo",
    X_c_th_c_th_ng_tin_Fact_c: "Xác thực",
    T_ng_ph_n_t_ch_v_x_c_minh: "Phân tích và xác thực thông tin.",
    Ph_n_t_ch_t_ng_v_bi_n_so_: "Tự động biên soạn kịch bản.",
    ang_t_o: "Đang tạo...",
    Generate_Script: "Tạo kịch bản",
    ang_so_n_k_ch_b_n: "Đang soạn kịch bản...",
    M_h_nh_AI_ang_ki_n_t_o_k_: "AI đang tự động soạn kịch bản.",
    FULL_VERBOSE_SCRIPT: "Kịch bản chi tiết",
    Copied_script: "Đã sao chép kịch bản!",
    Copy: "Sao chép",
    Words: "Số từ",
    Chars: "Ký tự",
    Est_Time: "Thời lượng",
    min: "phút",
    Fact_Check_Insight: "Xác thực",
    Analyzing_historical_data: "Đang phân tích dữ liệu...",
    Chapters_Script_Outline: "Sườn kịch bản",
    Chapter: "Chương",
    Continue: "Tiếp tục",
    Scene_Voiceovers: "Giọng Đọc",
    Design_sequential_visual_: "Dàn cảnh và tạo giọng thuyết minh.",
    Automatically_split_story: "Tự động chia cảnh",
    Processing: "Đang tạo...",
    Generate_Storyboard: "Tạo cảnh",
    Settings: "Cấu hình",
    Fullscreen: "Toàn màn hình",
    fullscreenError: "Lỗi khi kích hoạt toàn màn hình: {error}",
    txt_1_Voice_Actor: "1. Giọng đọc (Voice)",
    Select_voice: "Chọn giọng...",
    Test_voice: "Nghe thử",
    Generate_all_scene_voiceo: "Tạo toàn bộ giọng đọc",
    Loading: "Đang tải...",
    Generate_Voice: "Tạo Voice",
    txt_2_Split_Density: "2. Mật độ cảnh",
    Word_aligned_Maximizes_im: "Bám sát từng từ nói.",
    By_word: "⏱️ Theo từ",
    Fast_paced_vibrant_short_: "Nhịp nhanh, câu ngắn.",
    Short_sentence: "⚡ Câu ngắn",
    Default_balanced_standard: "Mặc định, cân bằng.",
    Long_sentence: "⚖️ Câu dài",
    Mixed_sentences_desc: "Kết hợp câu ngắn và dài.",
    Mixed_sentences: "🎭 Kết hợp",
    Logical_paragraph_aligned: "Theo đoạn văn.",
    Paragraph_density: "📖 Theo đoạn",
    Master_Narration_Voiceove: "Thuyết minh",
    LIVE_AUDIO_READY: "LIVE AUDIO READY",
    Audio_rendering_preview: "Nghe thử",
    Live_playing: "Đang phát",
    Deck_ready: "Sẵn sàng",
    Synthesizing_voice: "Đang tạo giọng...",
    Building_audio_waves_and_: "Kết xuất và đồng bộ âm thanh.",
    No_voiceover_synthesized_: "Chưa tạo voice.",
    AI_Speech_Channel: "Kênh AI",
    Female_Speaker: "Giọng Nữ",
    Male_Speaker: "Giọng Nam",
    Standard_Speaker: "Giọng Chuẩn",
    txt_16_bit_WAV: "16-bit WAV",
    txt_44_1kHz_Mono: "44.1kHz • Mono",
    Click_to_toggle_speech_ra: "Đổi tốc độ",
    x: "x",
    Download_voiceover_file: "Tải tệp",
    DL_VOICE: "TẢI XUỐNG",
    Console_Synchronization_l: "Nhật ký",
    Copied_alignments_ledger: "Đã sao chép nhật ký!",
    SYSTEM: "[SYSTEM]",
    Launching_Real_time_Align: "Đang khởi động đồng bộ...",
    PROCESS_Generating_audio_: "[PROCESS] Đang tạo giọng đọc...",
    Console_is_waiting_for_ti: "Console đang sẵn sàng chờ tệp đồng bộ...",
    Storyboard_splitting_path: "Chia cảnh",
    Select_Storyboard_Split_M: "Chọn cách chia cảnh",
    Switching_to_Audio_Voice_: "Dùng âm thanh gốc.",
    Audio_voice_mode: "Âm thanh gốc",
    Recommended: "Khuyên dùng",
    Align_scenes_timings_dyna: "Đồng bộ thời gian theo âm thanh.",
    Switching_to_full_text_sc: "Dùng kịch bản thuyết minh.",
    Script_mode: "Kịch bản chi tiết",
    Utilize_raw_screenplay_sc: "Dán kịch bản để tự động cắt cảnh.",
    AI_Speech: "Thuyết minh AI",
    External_Audio: "Tệp ghi âm",
    Female_speaker_AI: "Giọng nữ AI",
    Male_speaker_AI: "Giọng nam AI",
    Standard_voice: "Giọng thuyết minh",
    Smart_aligned_timeline_vo: "Đồng bộ thời gian",
    Reset: "Đặt lại",
    AI_Voice: "Thuyết minh AI",
    Simulated_Voice: "Giọng mô phỏng",
    Synthesized_audio_demo: "Bản demo tổng hợp âm",
    Exit_synth: "Hủy",
    AI_voiceover_not_compiled: "Chưa có voice AI.",
    Compile_AI_speech_at_step: "Tạo giọng đọc AI hoặc dùng giả lập.",
    Sample_Speech: "Giọng mẫu",
    Activated_simulated_speec: "Đã kết nối giọng mô phỏng.",
    Simulated_Voice_5: "Giọng giả lập",
    Linked_external_narration: "Tệp âm thanh",
    Replace: "Thay tệp",
    Remove: "Xóa",
    Drop_audio_file_now: "Buông tay để tải tệp...",
    Drag_audio_or_Click_to_up: "Kéo thả hoặc nhấn chọn tệp.",
    Supported_up_to_50MB_wav_: "Supported up to 50MB wav, mp3 formats",
    Paste_verbose_storyboard_: "Dán kịch bản phân cảnh...",
    Tip_Pasting_full_narratio: "Dán kịch bản giúp đồng bộ tốt hơn.",
    Modify_visual_configurati: "Cấu hình style",
    Veo_3_Creative_Studio_Dec: "Tạo Visual Veo 3",
    Collapse: "Thu gọn",
    Expand: "Mở rộng",
    Active_Drawing_Engine: "Model vẽ:",
    IMAGE_REFERENCE_NODE: "ẢNH THAM CHIẾU",
    Upload_style_images: "Tải ảnh mẫu",
    System_extracts_Style_Art: 'Học hỏi phong cách và màu sắc.',
    Style: "Phong cách:",
    Copied_style: "Đã sao chép phong cách!",
    Copy_style: "Sao chép phong cách",
    Extracting: "Đang đọc...",
    Extract_Style: "Trích phong cách",
    Applying: "Đang áp dụng...",
    Apply_Style: "Áp dụng",
    No_reference_images_uploa: "Chưa có hình ảnh tham chiếu nào được tải lên.",
    Bulk_visuals_sync_suite: "Đồng bộ ảnh loạt",
    Export_all_scene_prompts_: "Xuất prompt và đồng bộ ảnh.",
    Step_1_Bulk_copy_raw_prom: "1. Xuất prompt loạt",
    Copy_all_chronological_sc: "Sao chép prompt để dùng ngoài.",
    Copied_successfully: "Đã sao chép thành công!",
    Copy_All: "Copy tất cả",
    Step_2_Batch_upload_scene: "2. Tải ảnh loạt",
    Drag_drop_all_generated_i: "Kéo thả hoặc click chọn ảnh.",
    How_auto_alignment_works: "📌 Khớp nối thông minh tự động:",
    H_th_ng_s_ng_b_theo_t_n_f: "Đồng bộ tự động theo tên file.",
    txt_1_jpg: "1.jpg",
    txt_2_jpg: "2.jpg",
    ho_c_ch_a_ch_s_t_ng_ng_v_: ", hoặc chứa chữ số tương ứng với Phân cảnh. Nếu tên\n                          không khớp số, hệ thống tự động gắn tệp theo thứ tự\n                          chữ cái",
    A_Z: "A-Z",
    ph_n_ph_i_u_t_u_n_cu_i: "phân phối đều từ đầu đến cuối.",
    Aligns_based_on_number_in: "Aligns based on number indicators within file name:\n                          e.g.",
    or: "or",
    scene_2_jpg: "scene_2.jpg",
    Otherwise_distributes_sor: ".\n                          Otherwise distributes sorted filenames alphabetically\n                          (A-Z) sequentially.",
    Auto_Render_All_Scene_Art: "Vẽ toàn bộ",
    Process_all_storyboard_de: "Tự động vẽ ảnh cho phân cảnh.",
    Trigger_batch_AI_renderin: "Vẽ ảnh hàng loạt cho cảnh.",
    BATCH_RENDER: "Tạo hàng loạt",
    OPTIMIZE_PROMPTS: "Tối ưu AI",
    optimizingPrompts: "Đang tối ưu...",
    optimizePromptsSuccess: "Cải thiện mô tả hình ảnh thành công!",
    No_Storyboard_Scenes: "Chưa có cảnh",
    Click_button_below_to_sub: "Nhấn nút để tạo phân cảnh.",
    Generating_all_voices: "Đang tạo toàn bộ Voice...",
    MULTI_STEP_SYSTEM_FLOW_Di: "[MULTI-STEP SYSTEM FLOW] Đang chia phân cảnh...",
    System_is_synthesizing_te: "Hệ thống đang tiến hành chuyển đổi văn bản sang giọng đọc cho các phân cảnh.",
    Mapping_detailed_timeline: "Phân tích kịch bản thành các cảnh.",
    Drawing: "Đang vẽ...",
    s: "s",
    No_AI_image: "Chưa vẽ ảnh",
    No_description: "Chưa soạn kịch bản",
    Go_to_previous_page: "Quay lại trang trước",
    Previous: "Trang trước",
    Go_to_next_page: "Chuyển sang trang sau",
    Next: "Trang sau",
    Scene_Inspector: "Chi tiết cảnh",
    s_6: "s)",
    Scene_Artwork: "Ảnh phân cảnh",
    No_AI_Artwork_Rendered: "Chưa vẽ ảnh",
    Render_AI_image_matching_: "Vẽ ảnh AI theo cảnh.",
    Regen_AI: "Vẽ lại",
    Render_AI: "Vẽ ảnh",
    Upload_file: "Tải ảnh",
    Delete_Image: "Xóa ảnh",
    Duration: "Thời lượng",
    Camera_motion: "Chuyển động",
    FX: "Hiệu ứng",
    Narration_text: "Lời thuyết minh",
    Subtitle: "Phụ đề",
    Designer: "Thiết kế",
    Hide: "Thu nhỏ",
    Show: "Mở rộng",
    txt_1_Environment_Setting: "1. Bối cảnh (Setting):",
    misty_pine_forest_vintage: "rừng thông sương mù, phố cổ Hội An...",
    txt_2_Time_of_Day_Lighting: "2. Thời điểm & Ánh sáng (Lighting):",
    warm_golden_sunset_low_ke: "hoàng hôn vàng ấm, tia nắng rọi...",
    txt_3_Character_details: "3. Nhân vật & Biểu cảm (Character):",
    old_wise_magician: "chiến binh dũng mãnh, cô gái mỉm cười...",
    txt_4_Costume_Attire: "4. Trang phục (Costume):",
    rough_leather_boots: "áo giáp da, áo choàng nhung đỏ...",
    txt_5_Camera_Angle: "5. Góc máy quay (Camera Angle):",
    cinematic_close_up_portra: "chân dung cận cảnh sắc nét, panorama...",
    Writing: "Đang viết tự động...",
    Optimize_Prompt: "Tối ưu prompt",
    E_g_Blur: "E.g. Blur",
    E_g_Fade: "E.g. Fade",
    Cancel: "Hủy bỏ",
    Save_Changes: "Cập nhật",
    Back: "Quay lại",
    Select_visual_styles_defi: "Chọn style và quản lý phân cảnh.",
    Create_prompt_guides_and_: "Tạo câu lệnh và ảnh bìa.",
    Generating: "Đang tạo...",
    Generate_Thumbnails: "Tạo bìa",
    Thumbnail_Prompts_Input: "Ý tưởng ảnh bìa",
    INPUT_STATE: "TRẠNG THÁI NHẬP",
    Empty_script_Paste_here: "Kịch bản trống.",
    Batch_Count: "Số lượng:",
    idea: "ý tưởng",
    ideas: "ý tưởng",
    Reference_Image_Optional: "Ảnh tham chiếu (Tùy chọn)",
    Style_copied: "Đã sao chép phong cách",
    No_Thumbnail_Prompts: "Chưa có bìa",
    bulkRenderThumbnailsSuccess: "Đã hoàn thành tạo hàng loạt ảnh bìa!",
    Draft_eye_catching_visual: "Chưa có thiết kế bìa.",
    Draft_visual_arrangements: "Thiết kế bìa YouTube",
    Generate_Thumbnail: "Tạo ý tưởng",
    Drafting_CTR_thumbnail: "Đang tạo ảnh bìa...",
    Drafting_eye_catching_vis: "Thiết kế bố cục và màu sắc.",
    thumbnail: "ảnh bìa",
    No_Render_Done: "Chưa tạo ảnh",
    Look: "Phong cách",
    Copied_thumbnail_prompt: "Đã sao chép prompt bìa!",
    Copy_Prompt: "Sao chép prompt",
    Layout: "Bố cục",
    Font: "Font chữ",
    Color: "Màu sắc",
    Render_YouTube_mockup_thu: "Vẽ ảnh bìa bằng AI.",
    Render_Mockup: "Tạo ảnh",
    Recreate_Mockup: "Tạo lại",
    Form_tts_voices_with_dive: "Sinh thuyết minh tự động hoặc căn khớp mốc thời gian (Alignment)",
    Run_speech_audio_synthesi: "Khởi chạy luồng sinh giọng thuyết minh AI",
    Synthesizing: "Đang tạo...",
    Synthesize_Voice: "Tạo giọng đọc",
    Full_verbose_script: "Kịch bản thuyết minh toàn diện",
    txt_1_Vocal_timbre_expression: "1. Đặc trưng giọng đọc & diễn cảm",
    Choose_narrator_voices_em: "Lựa chọn phương thức đọc, giới tính biểu đạt và cảm xúc giọng văn.",
    System_Cloud_Speaker: "Chọn giọng đọc hệ thống & đám mây",
    Requires_Vietnamese_voice: "Cần giọng Việt",
    NARRATOR: "THUYẾT MINH VIÊN",
    CLOUD_AI: "AI ĐÁM MÂY",
    NATIVE_TTS: "TTS THIẾT BỊ",
    Male: "Giới tính: Nam",
    Female: "Giới tính: Nữ",
    Neutral: "Giới tính: Trung Tính",
    Custom_custom_defined_syn: "Giọng đọc chưa khớp với các mẫu lưu sẵn",
    Northern_female: "Nữ miền Bắc, nhẹ nhàng, tự nhiên",
    Northern_male: "Nam miền Bắc, trưởng thành, rõ ràng",
    Central_female: "Nữ miền Trung, ngọt ngào, truyền cảm",
    Central_male: "Nam miền Trung, trầm ấm, sâu lắng",
    Southern_female: "Nữ miền Nam, thân thiện, dễ thương",
    Southern_male: "Nam miền Nam, ấm áp, chân thực",
    Playful_kids_voiceover: "Trẻ em Việt ngộ nghĩnh, vui tươi sinh động",
    Google_free_female: "Giọng chuẩn nữ Google miễn phí",
    Google_free_male: "Giọng chuẩn nam Google miễn phí",
    Google_free_English_femal: "Giọng chuẩn nữ tiếng Anh Google miễn phí",
    FPT_female_monthly: "Giọng nữ FPT giới hạn chu kỳ theo tháng",
    FPT_male_monthly: "Giọng nam FPT giới hạn chu kỳ theo tháng",
    Zalo_female_daily: "Giọng nữ Zalo giới hạn chu kỳ theo ngày",
    Viettel_male_yearly: "Giọng nam Viettel giới hạn chu kỳ theo năm",
    Hifidelity_native_female_: "Giọng Gemini Nữ chuẩn, trong trẻo cao cấp",
    Deep_speaker_native_male_: "Giọng Gemini Nam trầm ấm, cực kỳ chuyên nghiệp",
    Muff_free_high_quality_cl: "Giọng đọc AI mặc định tối ưu theo kịch bản",
    Local_offline_system_voic: "Giọng offline trực tiếp từ thiết bị duyệt",
    Cloud_online_voice: "Giọng trực tuyến đám mây",
    Speed: "Tốc độ:",
    Pitch: "Tông:",
    Stop_preview: "Dừng nghe",
    Preview_current_voice: "Nghe thử",
    Change_voice: "Đổi giọng",
    Male_Voice: "Giọng Nam",
    Female_Voice: "Giọng Nữ",
    Neutral_Accent: "Giọng Trung tính",
    txt_2_Acoustic_master_control: "2. Bộ điều chỉnh âm thanh chuyên nghiệp",
    Refine_playback_rates_emo: "Chỉnh tốc độ, tông và âm lượng.",
    Speed_7: "Tốc độ",
    txt_0_5x: "0.5x",
    txt_2_0x: "2.0x",
    Pitch_8: "Tông giọng",
    Volume: "Âm lượng",
    Mute: "Tắt tiếng",
    Synchronicity_Journal: "Nhật ký đồng bộ",
    Aligned: "Đã liên kết",
    Click_the_button_below_to: "Vui lòng click nút dưới đây để tạo giọng đọc tự động hoặc tải lên file âm thanh của bạn.",
    Synthesize_AI_Voice: "Tạo giọng đọc",
    Alignment_Console_Ready: "Sẵn sàng đồng bộ",
    Once_voiceover_is_synthes: "Khi bạn tiến hành sinh thuyết minh, nhật ký chi tiết về mốc phụ đề Forced Alignment, phân chia cảnh và tỷ lệ khớp âm sẽ lập tức được ghi nhận tại đây.",
    syncing: "(đang xử lý...)",
    CONFIG: "[CONFIG]",
    Mapping_timelines_to_scen: "Cấu hình khung thời lượng...",
    STATUS: "[STATUS]",
    Aligning_subtitles: "Tính toán phụ đề...",
    Synchronizing: "Đang đồng bộ...",
    Forced_alignment_matches_: "Đồng bộ mốc thời gian phụ đề (2-5 giây)",
    Optimize_metadata_and_tri: "Sáng tạo tiêu đề và thẻ từ khóa tăng tương tác đề xuất",
    Optimizing: "Đang tạo...",
    Optimize_SEO: "Tối ưu SEO",
    SEO_Optimization_Input: "Nhập nội dung tham chiếu Tối ưu SEO",
    Number_of_Title_Variants_: "Số lượng tùy chọn cần tạo (Tiêu đề)",
    variants: "tùy chọn",
    Titles_Options_Group: "Đề xuất Tiêu đề Thu hút",
    No_SEO_Data: "Trống đề xuất SEO",
    Click_Optimize_Boost_at_t: "Nhấn Tối ưu hóa để tạo từ khóa.",
    Copied_title_to_clipboard: "Đã sao chép tiêu đề vào bộ nhớ tạm!",
    Copy_title: "Sao chép tiêu đề",
    Search: "Lực tìm:",
    CTR: "Thu hút (CTR):",
    Compet: "Cạnh tranh:",
    SEO_Score: "Điểm SEO:",
    Description_Options: "Đề xuất Mô tả Video",
    Descriptions_are_empty: "Mô tả đang trống.",
    Copied_description_to_cli: "Đã sao chép mô tả vào bộ nhớ tạm!",
    Copied_Hashtags_to_clipbo: "Đã sao chép Hashtags vào bộ nhớ tạm!",
    Copy_Hashtags: "Sao chép Hashtags",
    No_hashtags: "Chưa có thẻ",
    Copied_Tags_to_clipboard: "Đã sao chép Tags vào bộ nhớ tạm!",
    Copy_Tags: "Sao chép Tags",
    No_keywords: "Chưa có từ khóa",
    rendering_visual: "rendering visual",
    Default_Timeline_Image: "Ảnh Timeline Mặc định",
    Scene: "Phân cảnh",
    Camera_VFX: "Hiệu ứng máy quay",
    Nothing_to_simulate: "Không có phân cảnh để mô phỏng.",
    SIMULATOR_STATUS: "TRẠNG THÁI MÔ PHỎNG:",
    ACTIVE_RUNNING: "ĐANG CHẠY",
    PAUSED: "TẠM DỪNG",
    Stop_Simulation: "Dừng",
    Play_Simulation: "Mô phỏng",
    Professional_Project_Pack: "Lựa chọn Xuất bản kỹ thuật",
    Exports_timeline_JSON_fil: "Xuất dữ liệu dòng thời gian kịch bản tương thích trực tiếp phần mềm máy tính.",
    Construct_XML_track_metad: "Khởi tạo dữ liệu đa rãnh chuyển tiếp hoàn hảo cho ứng dụng chỉnh sửa phim.",
    Download_FCPXML_timing_fi: "Tải tập tin đồng bộ thời lượng chuyển cảnh cho ứng dụng phối màu.",
    Render_and_compile_full_p: "Dựng phim trực tiếp hoàn chỉnh có kèm lời thuyết minh và phụ đề đầy đủ.",
    Download_complete_CapCut_: "Tải trọn bộ dữ liệu lưu trữ cấu trúc thư mục con và mốc thời gian hoàn tất, mở ra là dùng ngay.",
    Download_SRT: "Tải phụ đề SRT",
    Extract_synced_subtitle_t: "Trích xuất dữ liệu mốc thời gian phụ đề chuẩn định dạng chạy chữ quốc tế.",
    Cloud_Exporter_Sync_Setup: "Cấu hình đồng bộ S3",
    https_s3_amazonaws_com_yo: "https://s3.amazonaws.com/your-bucket",
    Configured_bucket_coordin: "Đã liên kết bộ lưu trữ đám mây S3 thành công!",
    Save: "Lưu cấu hình",
    Image_Lightbox_Preview: "Xem chi tiết",
    Generation_Prompt: "Lệnh tạo ảnh (Prompt)",
    Download_Original: "Tải xuống ảnh gốc",
    Close_window: "Đóng cửa sổ",
    Voice_Registry: "Thư viện Giọng",
    Voices: "Giọng",
    Search_voices_registry_by: 'Tìm theo tên, ngôn ngữ ví dụ"vi-VN","gemini"...',
    Cloud_AI_Premium: "Cao cấp",
    Offline_Local_TTS: "Thiết bị",
    LOCALE: "KHU VỰC:",
    All: "Tất cả",
    Vietnamese: "Tiếng Việt",
    English: "Tiếng Anh",
    Premium_studio_quality_vo: "Giọng Premium chất lượng cao.",
    GENDER: "GIỚI TÍNH:",
    Male_9: "Giọng Nam",
    Female_10: "Giọng Nữ",
    No_speakers_found_matchin: "Không tìm thấy thuyết minh viên nào",
    Adjust_search_query_revok: "Hãy thử thay đổi từ khoá tìm kiếm, huỷ bớt bộ lọc hoặc chuyển đổi tab khác.",
    FEMALE: "NỮ",
    MALE: "NAM",
    NEUTRAL: "TRUNG TÍNH",
    Hifidelity_female_cloud_A: "Giọng Gemini Nữ chuẩn, trong trẻo cao cấp bậc nhất.",
    Hifidelity_male_cloud_AI: "Giọng Gemini Nam trầm ấm, cực kỳ thuyết phục và chuyên nghiệp.",
    Muff_free_cloud_AI_defaul: "Giọng đọc AI mặc định tối ưu hóa cho kịch bản.",
    Offline_system_synthesize: "Giọng offline xử lý trực tiếp trên trình duyệt của bạn.",
    Online_speech_voice: "Giọng đám mây trực tuyến chuẩn hóa.",
    Offline_Supported: "Hỗ trợ Offline",
    Online_API_Required: "Cần Internet",
    Listen_sample: "Nghe thử giọng mẫu",
    ACTIVE: "Thoại",
    SELECT: "Chọn",
    Switching_locks_subtitles: "Đổi giọng sẽ tải lại phụ đề.",
    APPLY: "ÁP DỤNG",
    WORKSPACE: "WORKSPACE",
    PROPS: "PROPS",
    General_Metadata: "General Metadata",
    Project_Hash: "Project Hash",
    Content_Target_Lang: "Content Target Lang",
    Format_Strategy: "Format Strategy",
    Active_Profiles: "Active Profiles",
    Narrator_ID: "Narrator ID",
    Vision_Identity: "Vision Identity",
    System_Error: "Lỗi hệ thống",
    Success: "Thành công",
    Failed_to_parse_cURL_comm: "✗ Lỗi phân tích lệnh cURL",
    v2_4_PRO: "v2.4 PRO",
    Live_Sync: "Đồng bộ trực tiếp",
    pts: "pts",
    USD: "USD",
    Sandbox: "Cổng Vẽ AI",
    text_slate_400_hover_text: "bg-slate-700 text-slate-100 shadow-sm",
    VI: "VI",
    EN: "EN",
    Sandbox_Config: "Cài đặt Cổng Vẽ",
    Active: "Đang hoạt động",
    Unlimited_Proxy: "Proxy không giới hạn",
    Saved: "Đã lưu!",
    Paste_cURL_from_Chrome_F1: "Dán lệnh cURL từ Chrome (F12)",
    Paste_full_cURL: "Dán toàn bộ mã cURL...",
    Extracted_Parameters: "Thông số đã trích xuất",
    Authorization: "Authorization",
    Project_ID: "Mã dự án",
    Session_ID: "Mã phiên",
    API_Mode: "Chế độ API",
    Saving: "Đang lưu...",
    Save_Config: "Lưu cấu hình",
    Synthesize_stories_design: "Quản lý, tối ưu phân cảnh và xuất video",
    en_US: "vi-VN",
    No_description_1: "Chưa có mô tả...",
    Open: "Mở",
    Confirm_Deletion: "Xác nhận xóa dự án",
    Are_you_sure_you_want_to_: "Bạn có chắc chắn muốn xóa dự án",
    This_action_cannot_be_und: "Hành động này không thể hoàn tác. Mọi kịch bản và cấu hình sẽ bị xóa vĩnh viễn.",
    Edit_Project: "Chỉnh sửa Dự án",
    E_g_Legends_of_Rome: "Ví dụ: Ký sự Nhà Tần",
    Write_custom_script_idea_: "Bản thảo video kể về sự ra đời của...",
    Niche_ideas: "Ý tưởng ngách",
    You_can_choice_History_Do: "Bạn có thể chọn thể loại Lịch Sử, Khoa Học hay True Crime để tái thiết phân cảnh chân thật nhất bằng Imagen 4.",
    Update: "Cập nhật",
    Inputs: "Đầu vào",
    Hook_Engine: "Sản xuất lời dẫn",
    Story_Expansion: "Nội dung và sự kiện",
    Storyboard: "Trục thời gian",
    Visuals: "Đồ họa và hình ảnh",
    Audio_Sync: "Âm thanh và phụ đề",
    SEO_Boost: "Tối ưu tìm kiếm",
    Video_Editorial: "Biên tập và xuất bản",
    Click_any_node_to_view_de: "Nhấp vào node để xem chức năng kỹ thuật",
    STAGE_0: "BƯỚC 0",
    Navigate_to_this_stage: "Di chuyển tới bước xử lý này",
    Jump_to_this_step: "Chuyển tới quy trình này",
    Close: "Đóng",
    Voice_Library: "Thư viện Giọng đọc",
    Search_2: "Tìm kiếm",
    Name_description: "Tên, mô tả...",
    Provider: "Nguồn giọng",
    Edge_Microsoft: "Edge (Microsoft)",
    ElevenLabs: "ElevenLabs",
    Minimax: "Minimax",
    Kokoro: "Kokoro",
    Clone: "Nhân bản",
    Vbee: "Vbee",
    Language: "Ngôn ngữ",
    English_3: "Tiếng Anh",
    Vietnamese_4: "Tiếng Việt",
    French: "Tiếng Pháp",
    German: "Tiếng Đức",
    Spanish: "Tiếng Tây Ban Nha",
    Japanese: "Tiếng Nhật",
    Korean: "Tiếng Hàn",
    Chinese: "Tiếng Trung",
    Gender: "Giới tính",
    Male_5: "Nam",
    Female_6: "Nữ",
    Age: "Độ tuổi",
    Young: "Trẻ",
    Middle_aged: "Trung niên",
    Elderly: "Người già",
    No_voices_found: "Không tìm thấy giọng đọc",
    Loading_7: "Đang tải...",
    Selected: "Đã chọn",
    Loading_8: "Đang tải...",
    Image_Generation_Settings: "Cấu hình tạo ảnh",
    Image: "Hình ảnh",
    Video: "Video",
    Aspect_Ratio: "Khung hình",
    Input_Method_Labs: "Phương thức nhập (Labs)",
    Type_Text: "Nhập chữ",
    Quick_Paste: "Dán nhanh",
    Sample_Count: "Số lượng mẫu",
    Imagen_3: "✨ Imagen 3",
    Nano_Banana_2: "🍌 Nano Banana 2",
    Labs_Sandbox: "🧪 Labs Sandbox",
    Chrome_Mode: "Chế độ Chrome",
    Chrome_Hidden: "Chạy ẩn Chrome",
    Chrome_Visible: "Mở trình duyệt Chrome",
    Generation_Speed: "Tốc độ tạo (số tab)",
    GeminiSpeed_1: "1",
    GeminiSpeed_3: "3",
    GeminiSpeed_5: "5",
    GeminiSpeed_7: "7",
    GeminiSpeed_10: "10",
    Batch_Delay: "Khoảng nghỉ hàng loạt",
    Batch_Delay_Default: "Mặc định (1-2s)",
    Batch_Delay_1s: "1s",
    Batch_Delay_2s: "2s",
    Batch_Delay_3s: "3s",
    Batch_Delay_Random_123: "Ngẫu nhiên 1-3s",
    cancellingBatchGen: "Đang dừng vẽ ảnh hàng loạt...",
    initializingBatchGen: "Đang chuẩn bị vẽ ảnh hàng loạt...",
    batchGenCancelled: "Đã dừng. Đã vẽ thành công {completedCount} ảnh.",
    generatingSceneBatch: "Đang vẽ phân cảnh {sceneId} ({currentIndex}/{totalToProcess})...",
    errorRenderingSceneBatch: "Lỗi phân cảnh {sceneId}: {error}",
    waitingBetweenScenes: "Chờ 3 giây...",
    batchGenSuccess: "Đã vẽ xong toàn bộ {completedCount} ảnh phân cảnh!",
    batchGenFailed: "Lỗi vẽ ảnh hàng loạt: {error}",
    alignmentLoaded: "Đã tải cấu hình phụ đề đồng bộ.",
    scriptPipelineError: "Lỗi kịch bản: {error}",
    syncLedgerSuccess: "=== ĐỒNG BỘ GIỌNG ĐỌC THÀNH CÔNG ({totalDuration}giây) ===\n",
    syncLedgerItem: '👉 Phân cảnh {index} ({startTime} --> {endTime}) | {duration}s | Phụ đề: "{script}..."\n',
    storyboardPipelineError: "Lỗi phân cảnh: {error}",
    imagePipelineError: "Lỗi tạo ảnh: {error}",
    imageUploadSuccess: "Đã tải ảnh phân cảnh {sceneId} thành công!",
    styleExtractionError: "Lỗi phân tích ảnh: {error}",
    applyStyleError: "Lỗi áp dụng phong cách: {error}",
    missingImagesWarning: "⚠️ Thiếu ảnh cho phân cảnh: {ids}.",
    mismatchImagesWarning: '⚠️ Sai số thứ tự: file "{fileName}" gán cho Phân cảnh {sceneId}.',
    bulkUploadSuccess: "Đã liên kết {count} ảnh phân cảnh!",
    promptGenError: "Lỗi tạo prompt: {error}",
    thumbnailPipelineError: "Lỗi tạo ảnh thu nhỏ: {error}",
    voiceSynthError: "Lỗi tạo giọng đọc: {error}",
    errorGeneratingVoiceover: "Lỗi tạo giọng thuyết minh: {error}",
    seoPipelineError: "Lỗi tối ưu SEO: {error}",
    renderingProgress: "Đang xuất video: {prog}%...",
    stopImageGen: "Dừng tiến trình tạo ảnh",
    cancelling: "Đang hủy...",
    ext_success_extract: "✓ Đã trích xuất thành công:",
    ext_bearer: "Bearer, ",
    ext_recaptcha: "reCAPTCHA, ",
    ext_streamchat: "Kiểu StreamChat (SSE)",
    ext_batch: "Kiểu Batch",
    apiKeysConfig: "Cấu hình khóa API",
    configured: "Đã nhập",
    notSet: "Chưa cấu hình",
    apiKeysDesc: "Các khóa này sẽ được ưu tiên sử dụng trước các cấu hình trong file .env",
    enterGeminiKey: "Nhập khóa API Gemini...",
    enterAi33Key: "Nhập mã AI33 TTS...",
    favorite: "Yêu thích",
    copyVoiceName: "Sao chép tên giọng",
    editVoice: "Sửa giọng đọc",
    deleteVoice: "Xóa giọng đọc",
    copyStyleDesc: "Sao chép phong cách",
    editStyle: "Sửa phong cách",
    deleteStyle: "Xóa phong cách",
    loadedFile: "Tải tệp thành công: {name}",
    pasteSamplePrompts: "Dán 2 prompt mẫu",
    clearAll: "Xóa toàn bộ",
    charNamePlaceholder: "Tên nhân vật",
    charBioPlaceholder: "Mô tả tiểu sử nhân vật...",
    noImageYet: "Chưa có ảnh",
    charFeaturePlaceholder: "Đặc tả nhân vật...",
    composition169: "Bố cục 16:9",
    focusTitle: "Tiêu điểm",
    downloadImage: "Tải ảnh về",
    uploadingImage: "Đang tải lên...",
    deleting: "Đang xóa...",
    copyNarration: "Sao chép thuyết minh",
    copySubtitle: "Sao chép phụ đề",
    copyAiImagePrompt: "Sao chép mô tả AI",
    totalScenesCount: "Tổng số phân cảnh: {count}",
    pageIndicator: "Trang {current} / {total}",
    noPhotoRenderedYet: "Chưa có hình ảnh được tạo cho PHÂN CẢNH {sceneId}. Hãy quay lại bước phân cảnh để tạo!",
    offlineRenderProgressText: "Đang kết xuất: {progress}%...",
    streamNotSupported: "Luồng dữ liệu không được hỗ trợ bởi trình duyệt này.",
    aligningVoiceWithWhisper: "Đang đồng bộ âm thanh bằng Whisper AI...",
    voiceAlignSuccess: "Đã đồng bộ thời lượng các phân cảnh khớp 1-1 theo giọng nói thật (Whisper AI)!",
    voiceAlignNoValidResult: "Không nhận được kết quả phân tích hợp lệ từ Whisper AI.",
    voiceAlignSceneNotFound: "Không tìm thấy thông tin đồng bộ cho phân cảnh {sceneId}.",
    voiceAlignError: "Lỗi đồng bộ giọng nói bằng Whisper AI. Vui lòng kiểm tra cài đặt Python/Whisper.",
    exportingCapcut: "Đang xuất CapCut...",
    exportingPremiere: "Đang xuất Premiere...",
    exportingDavinci: "Đang xuất DaVinci...",
    exportingVideo: "Đang kết xuất Video...",
    packagingZip: "Đang đóng gói ZIP...",
    exportingSRT: "Đang xuất SRT...",
    waitExportProcess: "Vui lòng chờ trong giây lát, tiến trình này có thể mất chút thời gian...",
    download: "Tải về",
    node6_settings_title: "Cấu Hình Sinh Độc Lập",
    node6_engine: "Cơ chế tạo",
    node6_engine_veo3: "Flow Veo 3 (Labs Flow)",
    node6_engine_gemini: "Gemini Room (Gemini Chat)",
    node6_gen_type: "Loại thành phẩm",
    node6_image: "Hình ảnh",
    node6_video: "Video",
    node6_aspect_ratio: "Tỷ lệ khung hình",
    node6_prompts_list: "Danh Sách Prompt",
    node6_sample_prompts: "Prompt Mẫu",
    node6_clear_workspace: "Xóa bộ nhớ",
    node6_placeholder: "Dán danh sách prompt tại đây, mỗi prompt một dòng...\nVí dụ:\n1. Một người que đi dưới mưa...\n2. Một người que đang cầm kiếm...",
    node6_detected_prompts: "Đã nhận diện: {count} prompts",
    node6_stop_gen: "DỪNG LẠI",
    node6_start_gen: "BẮT ĐẦU TẠO",
    node6_zip_tooltip: "Tải toàn bộ ZIP",
    node6_console_title: "Bảng Điều Khiển Sinh",
    node6_console_waiting: "Đang đợi bắt đầu tiến trình...",
    node6_library_title: "Kho Tài Nguyên Độc Lập",
    node6_library_empty: "Danh sách trống",
    node6_library_empty_desc: "Hãy nhập danh sách các mô tả ở cột bên trái để bắt đầu sinh hình ảnh hoặc video.",
    node6_prompt_label: "Prompt {id}",
    node6_badge_done: "XONG",
    node6_badge_error: "LỖI",
    node6_rendering: "Đang tạo...",
    node6_waiting: "Chờ sinh",
    node6_log_sample_loaded: "Đã nhập danh sách prompt mẫu.",
    node6_log_invalid_prompts: "Vui lòng nhập ít nhất một prompt hợp lệ.",
    node6_log_start: "Bắt đầu quy trình sinh độc lập...",
    node6_log_cancelled: "Đã hủy tiến trình sinh bởi người dùng.",
    node6_log_processing: "Đang xử lý prompt {index}/{total}...",
    node6_log_success: "Sinh thành công prompt {index} trong {duration} giây.",
    node6_log_api_error: "API không trả về kết quả hợp lệ.",
    node6_log_error: "Lỗi tại prompt {index}: {error}",
    node6_log_completed: "Đã hoàn thành toàn bộ danh sách.",
    node6_log_cancelling: "Đang gửi tín hiệu dừng...",
    node6_log_zip_empty: "Không có tệp tin thành công nào để đóng gói ZIP.",
    node6_log_zip_start: "Đang khởi tạo nén file ZIP...",
    node6_log_zip_success: "Tải ZIP thành công!",
    node6_log_zip_error: "Lỗi đóng gói file ZIP: {error}",
    node6_log_cleared: "Đã dọn dẹp bộ nhớ.",
    node7_title: "Biên tập CapCut",
    node7_desc: "Tự động hóa đồng bộ hình ảnh theo giọng đọc, tạo chuyển động góc quay, tự động chuyển cảnh và chèn hiệu ứng âm thanh chuyên nghiệp cho dự án CapCut.",
    node7_input_file_label: "1. Chọn tệp cấu hình dự án gốc (draft_content.json)",
    node7_choose_file_btn: "Chọn tệp dự án",
    node7_file_selected: "Đã chọn: {name}",
    node7_file_empty: "Chưa chọn tệp cấu hình dự án draft_content.json",
    node7_api_key_label: "2. Khóa API Google Gemini (Bắt buộc khi tạo hiệu ứng âm thanh)",
    node7_api_key_placeholder: "Nhập khóa API Gemini tại đây...",
    node7_sfx_folder_label: "3. Thư mục chứa các hiệu ứng âm thanh (Tùy chọn)",
    node7_choose_sfx_btn: "Chọn thư mục âm thanh",
    node7_sfx_selected: "Thư mục hiệu ứng âm thanh: {path}",
    node7_sfx_empty: "Chưa chọn thư mục hiệu ứng âm thanh",
    node7_status_ready: "SẴN SÀNG XỬ LÝ",
    node7_status_processing: "ĐANG XỬ LÝ...",
    node7_status_success: "XỬ LÝ HOÀN TẤT THÀNH CÔNG!",
    node7_status_failed: "ĐÃ XẢY RA LỖI",
    node7_status_canceled: "ĐÃ HỦY TIẾN TRÌNH",
    node7_run_btn: "CHẠY QUY TRÌNH TỐI ƯU",
    node7_select_all: "Chọn tất cả",
    node7_deselect_all: "Bỏ chọn tất cả",
    node7_console_title: "Bảng điều khiển tiến trình CapCut",
    node7_console_waiting: "Hệ thống sẵn sàng thực thi các tác vụ tối ưu hóa dòng thời gian...",
    node7_log_started: "Bắt đầu thực thi quy trình tối ưu hóa CapCut nâng cao...",
    node7_log_success: "Quy trình tối ưu hóa CapCut hoàn tất thành công!",
    node7_log_error: "Gặp lỗi trong quá trình xử lý: {error}",
    node7_log_missing_file: "Vui lòng chọn tệp cấu hình draft_content.json trước khi chạy!",
    node7_log_missing_api: "Vui lòng cung cấp khóa API Gemini để kích hoạt tính năng tạo hiệu ứng âm thanh bằng trí tuệ nhân tạo (AI)!",
    node7_log_missing_sfx: "Vui lòng chọn thư mục hiệu ứng âm thanh để kích hoạt tính năng tạo hiệu ứng âm thanh bằng trí tuệ nhân tạo (AI)!",
    node7_opt_sync: "1. Đồng bộ thời lượng hình ảnh và âm thanh (1-1)",
    node7_opt_music_mix: "2. Tự động chèn và lặp nhạc nền ngẫu nhiên",
    node7_opt_custom_order: "3. Sắp xếp thứ tự phân cảnh theo từ khóa âm thanh",
    node7_opt_randomize: "4. Xáo trộn ngẫu nhiên thứ tự các phân cảnh",
    node7_opt_motion: "5. Tạo hiệu ứng thu phóng và chuyển động góc quay tự động",
    node7_opt_transition: "6. Tự động thêm hiệu ứng chuyển cảnh giữa các đoạn",
    node7_opt_clear_trans: "7. Xóa toàn bộ hiệu ứng chuyển cảnh hiện có",
    node7_opt_fill_canvas: "8. Tự động kéo giãn hình ảnh vừa khít khung hình",
    node7_opt_normalize: "9. Chuẩn hóa âm lượng tự động về mức tiêu chuẩn",
    node7_opt_reverse: "10. Đảo ngược thứ tự dòng thời gian của các phân cảnh",
    node7_opt_subtitles: "11. Đồng bộ phông chữ và kiểu dáng phụ đề chuyên nghiệp",
    node7_opt_sfx: "12. Tự động tạo và ghép hiệu ứng âm thanh bằng trí tuệ nhân tạo (AI)",
    node7_placeholder_file: "Nhập đường dẫn tuyệt đối đến tệp draft_content.json...",
    node7_placeholder_sfx: "Nhập đường dẫn tuyệt đối đến thư mục chứa hiệu ứng âm thanh...",
    node7_placeholder_audio_list: "Nhập các từ khóa âm thanh, ngăn cách bằng dấu phẩy (Ví dụ: intro, voice, outro)",
    node7_opt_title: "Các tùy chọn tự động hóa và tối ưu hóa",
    node7_audio_order_label: "Danh sách từ khóa sắp xếp âm thanh ưu tiên:",
    node7_log_started_dialog: "Đang mở cửa sổ hệ thống để chọn tệp tin...",
    node7_log_started_folder: "Đang mở cửa sổ hệ thống để chọn thư mục...",
    node7_log_selected_file: "Đã chọn tệp cấu hình: {path}",
    node7_log_selected_folder: "Đã chọn thư mục âm thanh: {path}",
    node7_log_canceled_file: "Đã hủy bỏ việc chọn tệp tin cấu hình.",
    node7_log_canceled_folder: "Đã hủy bỏ việc chọn thư mục âm thanh.",
    node7_log_error_file: "Lỗi phát sinh khi chọn tệp cấu hình: {error}",
    node7_log_error_folder: "Lỗi phát sinh khi chọn thư mục âm thanh: {error}",
    node7_log_calling_backend: "Đang kết nối với hệ thống dịch vụ để thực thi thuật toán...",
    node7_log_backup_saved: "Tệp sao lưu dự án đã được tạo và lưu trữ an toàn (.backup_ultra).",
    dashboardCreatorInfo: "Thông tin tài khoản",
    dashboardAICreator: "Nhà Sáng Tạo AI",
    dashboardMemberPro: "Thành viên V2.4 Pro",
    dashboardCreditsBalance: "Số dư tài khoản",
    dashboardPoints: "điểm",
    dashboardSyncedRealtime: "Đã quy đổi theo thời gian thực",
    dashboardEstimatedCost: "Chi phí tạm tính",
    dashboardAI_Metrics: "Chi phí các tác vụ AI",
    dashboardLatestProject: "Dự án mới nhất",
    dashboardNoDesc: "Không có mô tả cho dự án này.",
    dashboardOpenStudio: "Mở phòng sáng tạo",
    dashboardWelcome: "Chào mừng bạn đến với Vidify Studio",
    dashboardWelcomeDesc: "Hãy tạo một dự án video AI mới ở tab Nội dung để bắt đầu hành trình sản xuất video tự động của bạn.",
    dashboardGoToContent: "Đến mục Nội dung",
  },
};
