export const CAPCUT_CONFIG = {
  ACTIVE_FOLDER_UUID: "517bd185-0d13-49a4-8227-e73216acc7a9",
  LOCAL_DRAFT_PATH_PREFIX: "C:/CapCut/User Data/Drafts",
  CLIENT_VERSION: "4.8.1",
  DEVICE_ID: "ai-studio-pc-pro-export",
  SYSTEM_INFO: "Windows/MacOS PC Engine",
  AUTHOR: "AI Video Factory Pro",
  USER_ID: "AI_Studio_Power_User",
  CANVAS_WIDTH: 1920,
  CANVAS_HEIGHT: 1080,
  CANVAS_RATIO: "16:9",
  FPS: 30,
  RESOLUTION: "1080p",
  RATE_CONTROL: "vbr",
  BIT_RATE: 8000,
  COVER_FILENAME: "draft_cover.jpg",
  COVER_MOCK_CONTENT: "Mock Cover Binary Space",
  AUDIO_NARRATION_FILENAME: "audio_narration.wav",
  ORIGINAL_VOICE_FILENAME: "original_voice.wav",
  AUDIO_NARRATION_MOCK_CONTENT: "Mock Audio Stream Narration Voice Placeholder",
  AUDIO_SEGMENT_MOCK_CONTENT: "Mock Audio Stream Segment Placeholder",
  SOURCE_PLATFORM_TTS: "AI Video Factory TTS Segmented",
  DRAFT_CONTENT_FILENAME: "draft_content.json",
  DRAFT_CONTENT_BAK_FILENAME: "draft_content.json.bak",
  ATTACHMENT_EDITING_FILENAME: "attachment_editing.json",
  ATTACHMENT_PC_COMMON_FILENAME: "attachment_pc_common.json",
  DRAFT_EXTRA_FILENAME: "draft.extra",
  DRAFT_AGENCY_CONFIG_FILENAME: "draft_agency_config.json",
  DRAFT_BIZ_CONFIG_FILENAME: "draft_biz_config.json",
  DRAFT_META_INFO_FILENAME: "draft_meta_info.json",
  DRAFT_SETTINGS_FILENAME: "draft_settings",
  DRAFT_VIRTUAL_STORE_FILENAME: "draft_virtual_store.json",
  KEY_VALUE_FILENAME: "key_value.json",
  PERFORMANCE_OPT_FILENAME: "performance_opt_info.json",
  TEMPLATE_TMP_FILENAME: "template-2.tmp",
  TIMELINE_LAYOUT_FILENAME: "timeline_layout.json",
  EXPORT_BUNDLE_SUFFIX: "_CapCut_Project_Bundle.zip",
  EXPORT_ZIP_ROUTE: "/api/pipeline/export-zip",
  RESOURCES_IMAGES_DIR: "Resources/images",
} as const;
