export enum EXPORT_TYPES {
  CAPCUT = "capcut",
  PREMIERE = "premiere",
  ZIP = "zip",
  SRT = "srt",
}

export enum LogEvent {
  GENERAL_ERROR = "GENERAL_ERROR",
  ERROR_LOADING_SANDBOX = "ERROR_LOADING_SANDBOX",
  ERROR_SYNCING_SANDBOX = "ERROR_SYNCING_SANDBOX",
  PREVIEW_PLAYBACK_FAILED = "PREVIEW_PLAYBACK_FAILED",
  PREVIEW_DSP_FAILED = "PREVIEW_DSP_FAILED",
  CLOUD_PREVIEW_FAILED = "CLOUD_PREVIEW_FAILED",
  FAILED_LOAD_VOICES = "FAILED_LOAD_VOICES",
  FAILED_COPY_PROMPTS = "FAILED_COPY_PROMPTS",
  ERROR_READING_REF_IMAGES = "ERROR_READING_REF_IMAGES",
  STYLE_EXTRACTION_ERR = "STYLE_EXTRACTION_ERR",
  ERROR_READING_CHAR_IMAGES = "ERROR_READING_CHAR_IMAGES",
  ERROR_READ_MATCHED_FILE = "ERROR_READ_MATCHED_FILE",
  ERROR_READ_SEQ_FILE = "ERROR_READ_SEQ_FILE",
  ERROR_READ_THUMB_REF_IMAGES = "ERROR_READ_THUMB_REF_IMAGES",
  BATCH_SCENE_FAILED = "BATCH_SCENE_FAILED",
  FAILED_TO_PARSE_NDJSON_LINE = "Failed to parse NDJSON line",
  ERROR_RENDERING_SCENE_BATCH = "ERROR_RENDERING_SCENE_BATCH",
  BATCH_GEN_FAILURE = "BATCH_GEN_FAILURE",
  ERROR_GEN_DETAILED_PROMPT = "ERROR_GEN_DETAILED_PROMPT",
  SYNTHESIZE_ON_THE_FLY_FAILED = "SYNTHESIZE_ON_THE_FLY_FAILED",
  UNIFIED_SCENE_VOICE_GEN_FAILED = "UNIFIED_SCENE_VOICE_GEN_FAILED",
  UNIFIED_SEGMENT_VOICE_GEN_FAILED = "UNIFIED_SEGMENT_VOICE_GEN_FAILED",
  FAILED_DECODE_AUDIO_DURATION = "FAILED_DECODE_AUDIO_DURATION",
  OFFLINE_RENDERING_ERROR = "OFFLINE_RENDERING_ERROR",
  AUDIO_PLAYBACK_FAILED = "AUDIO_PLAYBACK_FAILED",
  COVER_IMAGE_CANVAS_CAPTURE_FAILED = "COVER_IMAGE_CANVAS_CAPTURE_FAILED",
  FAILED_FETCH_SCENE_IMAGE = "FAILED_FETCH_SCENE_IMAGE",
  FAILED_FETCH_NARRATION = "FAILED_FETCH_NARRATION",
  FAILED_DECODE_NARRATION_SLICE = "FAILED_DECODE_NARRATION_SLICE",
  FAILED_TO_CALL_AI_VOICE_ALIGN = "FAILED_TO_CALL_AI_VOICE_ALIGN",
  FAILED_PACKAGE_SLICED_VOICE = "FAILED_PACKAGE_SLICED_VOICE",
  CAPCUT_ZIP_GEN_ERROR = "CAPCUT_ZIP_GEN_ERROR",
  STYLE_EXTRACTION_ERROR = "STYLE_EXTRACTION_ERROR",
  BATCH_STYLE_REWRITE_FAILED_CHUNK = "BATCH_STYLE_REWRITE_FAILED_CHUNK",
  REWRITE_PROMPTS_ERROR = "REWRITE_PROMPTS_ERROR",
  BATCH_PROMPT_OPTIMIZE_FAILED_CHUNK = "BATCH_PROMPT_OPTIMIZE_FAILED_CHUNK",
  OPTIMIZE_PROMPTS_ERROR = "OPTIMIZE_PROMPTS_ERROR",
  BATCH_STYLE_REWRITE_FAILED_THUMBNAILS = "BATCH_STYLE_REWRITE_FAILED_THUMBNAILS",
  REWRITE_THUMBNAILS_ERROR = "REWRITE_THUMBNAILS_ERROR",
  CHARACTER_ANALYSIS_ERROR = "CHARACTER_ANALYSIS_ERROR",
  CHARACTER_EXTRACTION_ERROR = "CHARACTER_EXTRACTION_ERROR",
  BATCH_CHARACTER_REWRITE_FAILED_CHUNK = "BATCH_CHARACTER_REWRITE_FAILED_CHUNK",
  REWRITE_PROMPTS_CHARACTER_ERROR = "REWRITE_PROMPTS_CHARACTER_ERROR",
  ERROR_GENERATING_HOOKS = "ERROR_GENERATING_HOOKS",
  AUTO_HOOK_GENERATION_FAILED_FALLING_BACK = "Auto hook generation failed, falling back",
  ERROR_REWRITING_SCRIPT = "ERROR_REWRITING_SCRIPT",
  DETAILED_PROMPT_ERROR = "DETAILED_PROMPT_ERROR",
  ERROR_GENERATING_STORYBOARD_CHUNKING = "ERROR_GENERATING_STORYBOARD_CHUNKING",
  ERROR_GENERATING_STORYBOARD_GEMINI = "ERROR_GENERATING_STORYBOARD_GEMINI",
  ERROR_GENERATING_SEO = "ERROR_GENERATING_SEO",
  ERROR_GENERATING_THUMBNAILS_PROMPTS = "ERROR_GENERATING_THUMBNAILS_PROMPTS",
  TTS_PIPELINE_ERROR = "TTS_PIPELINE_ERROR",
  GENERATE_IMAGE_ROUTE_ERROR = "GENERATE_IMAGE_ROUTE_ERROR",
  GENERATE_BATCH_IMAGES_ROUTE_ERROR = "GENERATE_BATCH_IMAGES_ROUTE_ERROR",
  CLEAN_BATCH_IMAGES_ROUTE_ERROR = "CLEAN_BATCH_IMAGES_ROUTE_ERROR",
  ERROR_READ_MERGED_AUDIO = "ERROR_READ_MERGED_AUDIO",
  ERROR_FFMPEG_MERGE = "ERROR_FFMPEG_MERGE",
  UNEXPECTED_ERROR_MERGE_AUDIO = "UNEXPECTED_ERROR_MERGE_AUDIO",
  CAPCUT_ULTRA_PROCESS_FAILED = "CAPCUT_ULTRA_PROCESS_FAILED",
  CAPCUT_ULTRA_FS_FAILED = "CAPCUT_ULTRA_FS_FAILED",
}

export enum ErrorMessage {
  PROJECT_LOAD_ERROR = "Lỗi tải chi tiết dự án",
  MISSING_AUDIO_URL_FROM_SYNTHESIS = "Missing audio URL from synthesis",
  FAILED_TO_FETCH = "Failed to fetch",
  NO_SCENES_TO_RENDER = "No scenes to render",
  COULD_NOT_INITIALIZE_2D_CONTEXT = "Could not initialize 2D context",
  MISSING_SCENE_SCRIPT = "Missing scene script",
  NO_AUDIO_CHUNKS_PROVIDED = "No audio chunks provided",
  FAILED_TO_READ_MERGED_AUDIO_FILE = "Failed to read merged audio file",
  INTERNAL_SERVER_ERROR = "Internal server error: ",
  CAPCUT_ULTRA_OPTIMIZATION_ERROR = "Lỗi xử lý tối ưu hóa.",
  FAILED_TO_PARSE_NDJSON_LINE = "Failed to parse NDJSON line",
}

export enum VoicePresetId {
  PRESET_VI_BAC_FEMALE = "preset-vi-bac-female",
  PRESET_VI_BAC_MALE = "preset-vi-bac-male",
  PRESET_VI_TRUNG_FEMALE = "preset-vi-trung-female",
  PRESET_VI_TRUNG_MALE = "preset-vi-trung-male",
  PRESET_VI_NAM_FEMALE = "preset-vi-nam-female",
  PRESET_VI_NAM_MALE = "preset-vi-nam-male",
  PRESET_VI_KID = "preset-vi-kid",
  ELEVENLABS_CLOUD_VI = "elevenlabs-cloud-vi",
  AZURE_CLOUD_VI_HOAIMY = "azure-cloud-vi-hoaimy",
  AZURE_CLOUD_VI_NAMMINH = "azure-cloud-vi-namminh",
  GOOGLE_CLOUD_VI_A = "google-cloud-vi-a",
  GOOGLE_CLOUD_VI_B = "google-cloud-vi-b",
  OPENAI_TTS_ALLOY = "openai-tts-alloy",
  OPENAI_TTS_NOVA = "openai-tts-nova",
}

export enum SplitStrategy {
  MIXED_SENTENCES = "mixed_sentences",
  ULTRADENSE = "ultradense",
  WORD = "word",
  HYPERDENSE = "hyperdense",
  SHORT_SENTENCE = "short_sentence",
  HIGHPACED = "highpaced",
  DRAMATIC = "dramatic",
  PARAGRAPH = "paragraph",
  EPIC = "epic",
  CINEMATIC = "cinematic",
  ARTISTIC = "artistic",
  SLOWPACED = "slowpaced",
  SUPER_SLOW = "super_slow",
  SENTENCE = "sentence",
  DOCUMENTARY = "documentary",
  LONG_SENTENCE = "long_sentence",
}

export enum VideoGenre {
  HISTORY = "History",
  TRUE_CRIME = "True Crime",
  SCIENCE = "Science",
  PSYCHOLOGY = "Psychology",
  PHILOSOPHY = "Philosophy",
  STORYTELLING = "Storytelling",
}

export enum MimeType {
  WAV = "audio/wav",
  MPEG = "audio/mpeg",
  JPEG = "image/jpeg",
}

export enum UltraStreamLogType {
  LOG = "log",
  ERROR_LOG = "error_log",
}

export enum LogLevel {
  INFO = "info",
  SUCCESS = "success",
  WARN = "warn",
  ERROR = "error",
}

export enum SceneDensity {
  THEO_TU = "THEO_TU",
  CAU_NGAN = "CAU_NGAN",
  CAU_KET_HOP = "CAU_KET_HOP",
  CAU_DAI = "CAU_DAI",
  THEO_DOAN = "THEO_DOAN",
}

export enum PromptStatus {
  IDLE = "idle",
  RUNNING = "running",
  SUCCESS = "success",
  ERROR = "error",
}

export enum ThumbnailActionPosition {
  TOP = "top",
  EMPTY = "empty",
}

export enum AppTheme {
  LIGHT = "light",
  DARK = "dark",
}

export enum AppLanguage {
  VI = "vi",
  EN = "en",
}

